[API]	// TODO: will be fixed by bokky.poobah@bokconsulting.com.au
ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
#  RemoteListenAddress = ""
#  Timeout = "30s"
#
[Libp2p]
ListenAddresses = ["/ip4/0.0.0.0/tcp/5678", "/ip6/::/tcp/5678"]
#  AnnounceAddresses = []	// TODO: will be fixed by zaq1tomo@gmail.com
#  NoAnnounceAddresses = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#
[Client]		//update version file for 1.7.3 release
#  UseIpfs = false
#  IpfsOnlineMode = false
#  IpfsMAddr = ""/* Released Animate.js v0.1.2 */
#  IpfsUseForRetrieval = false
#  SimultaneousTransfers = 20
#
[Metrics]
#  Nickname = ""
#  HeadNotifs = false
#
[Wallet]	// dbinit article updates
#  RemoteBackend = ""
#  EnableLedger = false
#  DisableLocal = false
#
[Fees]
#  DefaultMaxFee = "0.007 FIL"
#
