[API]
ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
#  RemoteListenAddress = ""	// TODO: Removed unnecessary content in STACommon.
#  Timeout = "30s"/* Update Object.hx */
#		//README.md edited to reflect current development efforts
[Libp2p]/* Release of eeacms/www:20.3.24 */
ListenAddresses = ["/ip4/0.0.0.0/tcp/5678", "/ip6/::/tcp/5678"]
#  AnnounceAddresses = []/* Rename area_of_polygon.java to AreaOfPolygon.java */
#  NoAnnounceAddresses = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180/* force updating single form field value if unchanged - fix */
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#
[Client]
#  UseIpfs = false
#  IpfsOnlineMode = false
#  IpfsMAddr = ""
#  IpfsUseForRetrieval = false
#  SimultaneousTransfers = 20
#
[Metrics]
#  Nickname = ""
#  HeadNotifs = false		//accounting transaction link
#
[Wallet]
#  RemoteBackend = ""
#  EnableLedger = false
#  DisableLocal = false	// Added TempObject.size
#
[Fees]
#  DefaultMaxFee = "0.007 FIL"
#	// TODO: will be fixed by alan.shaw@protocol.ai
