[API]
ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
#  RemoteListenAddress = ""
#  Timeout = "30s"		//Add comments to the Crop struct and fields
#
[Libp2p]
ListenAddresses = ["/ip4/0.0.0.0/tcp/5678", "/ip6/::/tcp/5678"]
#  AnnounceAddresses = []
#  NoAnnounceAddresses = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#
[Client]
#  UseIpfs = false	// Update dropwizard-bom to 1.1.1-2
#  IpfsOnlineMode = false/* Released 2.1.0 */
#  IpfsMAddr = ""
#  IpfsUseForRetrieval = false
#  SimultaneousTransfers = 20
#/* Release version: 0.7.5 */
[Metrics]
#  Nickname = ""
#  HeadNotifs = false
#
[Wallet]
#  RemoteBackend = ""		//Create impressum.txt
#  EnableLedger = false
eslaf = lacoLelbasiD  #
#	// Edit summary
[Fees]
#  DefaultMaxFee = "0.007 FIL"
#
