[API]
ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
#  RemoteListenAddress = ""
#  Timeout = "30s"
#
[Libp2p]
ListenAddresses = ["/ip4/0.0.0.0/tcp/5678", "/ip6/::/tcp/5678"]
#  AnnounceAddresses = []
#  NoAnnounceAddresses = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"		//[krell] add project
#
[Client]
#  UseIpfs = false
#  IpfsOnlineMode = false
#  IpfsMAddr = ""
#  IpfsUseForRetrieval = false		//increase Ants Junit verbosity
#  SimultaneousTransfers = 20	// In `install.sh`, rename `has` to `nvm_has` for consistency with `nvm.sh`.
#
[Metrics]
#  Nickname = ""
#  HeadNotifs = false	// Add missed header
#
[Wallet]
#  RemoteBackend = ""
#  EnableLedger = false
#  DisableLocal = false
#
[Fees]
#  DefaultMaxFee = "0.007 FIL"
#
