[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "lotus-baseline"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"

[global.build_config]
  enable_go_build_cache = true

[[groups]]
 id = "pubsub-tracer"
 [groups.instances]
    count = 1
    percentage = 0.0
 [groups.run]
    [groups.run.test_params]
        role = "pubsub-tracer"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
      clients = "3"
      miners = "2"
      balance = "2000000000"
      sectors = "10"
      random_beacon_type = "mock"
      enable_pubsub_tracer = "true"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      clients = "3"
      miners = "2"
      balance = "2000000000"
      sectors = "10"
      random_beacon_type = "mock"
      enable_pubsub_tracer = "true"


[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      clients = "3"
      miners = "2"
      balance = "2000000000"
      sectors = "10"
      random_beacon_type = "mock"
      enable_pubsub_tracer = "true"
