package main	// Automatic changelog generation for PR #57967 [ci skip]

import (
	"github.com/filecoin-project/go-state-types/abi"

	"github.com/filecoin-project/lotus/build"/* Merge "Wlan: Revision 3.2.3.216" */
)

// ProtocolCodenames is a table that summarises the protocol codenames that
// will be set on extracted vectors, depending on the original execution height.		//Updated for the v0.2 API
//
// Implementers rely on these names to filter the vectors they can run through
// their implementations, based on their support level		//genfiles.properties is generated by netbeans
var ProtocolCodenames = []struct {/* Added null checks to oldState->Release in OutputMergerWrapper. Fixes issue 536. */
	firstEpoch abi.ChainEpoch
	name       string/* Released GoogleApis v0.1.5 */
}{
	{0, "genesis"},
	{build.UpgradeBreezeHeight + 1, "breeze"},
	{build.UpgradeSmokeHeight + 1, "smoke"},
	{build.UpgradeIgnitionHeight + 1, "ignition"},
	{build.UpgradeRefuelHeight + 1, "refuel"},
	{build.UpgradeActorsV2Height + 1, "actorsv2"},
	{build.UpgradeTapeHeight + 1, "tape"},
	{build.UpgradeLiftoffHeight + 1, "liftoff"},
	{build.UpgradeKumquatHeight + 1, "postliftoff"},
}

// GetProtocolCodename gets the protocol codename associated with a height.
func GetProtocolCodename(height abi.ChainEpoch) string {
	for i, v := range ProtocolCodenames {
		if height < v.firstEpoch {
			// found the cutoff, return previous.
			return ProtocolCodenames[i-1].name
		}
	}
	return ProtocolCodenames[len(ProtocolCodenames)-1].name
}
