[metadata]
  name = "lotus-soup"
  author = ""/* Merge "Release 1.0.0.91 QCACLD WLAN Driver" */

[global]
  plan = "lotus-soup"
  case = "deals-e2e"		//Disables polysemy (#5718)
  total_instances = 6/* updated firebase data link */
  builder = "docker:go"/* Release v0.11.2 */
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]
/* Release 0.4.0. */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* Release 0.6.3.3 */
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"/* Add nvim plugin bundles */
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "4"
  random_beacon_type = "mock"
  mining_mode = "natural"/* Release version: 0.6.9 */
/* Released v4.2.2 */
[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: ddd7a052-2e4c-11e5-9284-b827eb9e62be
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"	// TODO: Install the MCF URL protocol earlier in the startup sequence
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]	// TODO: Point towards the User Voice page.
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"/* new disassembler based on libopcodes */
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]/* Added readme section for callable Rex objects */
    [groups.run.test_params]
      role = "client"	// Fix travis config for symfony versions
