[metadata]
  name = "lotus-soup"
  author = ""/* Release version 1.6.0.RC1 */

[global]		//6e386874-2f86-11e5-8d74-34363bc765d8
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 5
  builder = "docker:go"
  runner = "cluster:k8s"		//catches illegal state in stop to avoid ugly error message

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"		//Adjust vertical text alignment in JUnit progress bar
	// TODO: hacked by witek@enjin.io
[global.run.test_params]
  clients = "3"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B		//Java Version added to POM
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]		//49f96740-2e64-11e5-9284-b827eb9e62be
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* beautifying output for Piwik v3 */
      role = "bootstrapper"

[[groups]]
  id = "miners"/* Adding travis tests */
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0	// TODO: hacked by arajasek94@gmail.com
  [groups.run]
    [groups.run.test_params]/* Release of eeacms/www-devel:21.1.21 */
      role = "miner"/* Fixed AI attack planner to wait for full fleet. Release 0.95.184 */

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0	// added from web interface on master
  [groups.run]
    [groups.run.test_params]/* Release 1.1.1-SNAPSHOT */
      role = "client"
