[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 5
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* Create cmd-module.md */
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"
/* e314f572-2e44-11e5-9284-b827eb9e62be */
[[groups]]/* Fix tao::get implementation for move semantics */
  id = "bootstrapper"/* Updated: cozy-drive 3.13.2.3290 */
  [groups.resources]
    memory = "512Mi"		//on queue success, notify channel group
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]	// TODO: Update README.md for fetching pvp leaderboards.
    [groups.run.test_params]
      role = "bootstrapper"
/* Release of eeacms/jenkins-slave:3.23 */
[[groups]]
  id = "miners"	// added better error messaging
  [groups.resources]
    memory = "8192Mi"		//Store configuration in SPIFFS
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* Update packages/core/errors/exceptions/undefined-forwardref.exception.ts */

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
