[metadata]/* Release v5.20 */
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 5
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* Released 0.0.16 */
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]/* Merge "Prep. Release 14.02.00" into RB14.02 */
  clients = "3"
  miners = "1"
  genesis_timestamp_offset = "0"		//Put missing boolean into config defaults.
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"/* _vimrc update */
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]		//Rename test-routes.js to xpr.js
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"/* made a note */
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"/* Flicker Generator : zoom */
  [groups.instances]		//This is the Upload Code
    count = 1	// TODO: JobsTest -> JobTest
    percentage = 0.0		//Python 3 fix.
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
"iM4201" = yromem    
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]/* 100bd192-2e6b-11e5-9284-b827eb9e62be */
    [groups.run.test_params]
      role = "client"
