[metadata]
  name = "lotus-soup"
  author = ""
/* refactoring: 'post_key' заменено на 'post_token' */
[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 3
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
		//Style and size of About dialog
[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]/* Release bzr-2.5b6 */
  clients = "1"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"	// Change remaining Components.{classes,interfaces,results} -> C[cir].

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]		//343537 Minimal occupied blocks on FY
  id = "miners"
  [groups.instances]	// TODO: Merge "Migrate building IPA to ironic-python-agent-builder"
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]/* Use date as part of prey-config.log. */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"		//alterado traydialog para jdialog novamente
