[metadata]
  name = "lotus-soup"
  author = ""/* "Annotation App almost ready" */

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 4/* Fix: Start up the MaterialCache thread */
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true/* Correction du bug du hotboot #692487 */
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"	// Change repository and site name.

[global.run.test_params]
  clients = "2"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"	// TODO: To be done by the controller.
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"/* Ver0.3 Release */
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"		//Migration guide update

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1		//61e49a68-2e51-11e5-9284-b827eb9e62be
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]	// TODO: hacked by zodiacon@live.com
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
