[metadata]
  name = "lotus-soup"	// Merge "Revert "Temporarily stop booting nodes in inap-mtl01""
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 3
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "1"
  miners = "1"	// TODO: Create replace-empty-anchor-links
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B		//[ issue #19 ] SPARQL Dispatcher RequestHandler (Query + Update) 
  sectors = "10"
  random_beacon_type = "mock"/* Merge "Modularize new features in Release Notes" */
  mining_mode = "natural"

[[groups]]/* Use updated version 1.3 (r36) of google-gflags */
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"/* Completed a one ball auton sequence */
