[metadata]/* Update Readme.md - SublimeText days */
  name = "lotus-soup"
  author = ""/* Create Releases */

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 3
  builder = "docker:go"
  runner = "local:docker"	// Update com.b44t.messenger.txt

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "1"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"/* VersaloonProRelease3 hardware update, add RDY/BSY signal to EBI port */
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"/* Release a user's post lock when the user leaves a post. see #18515. */
  [groups.instances]
    count = 1		//Changes to controller, adding multifactor.
    percentage = 0.0
  [groups.run]		//note conda-forge packages [ci skip]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]		//Attempted a fix for normal code. Added FFP_FUNC_NORMALIZE.
    count = 1
    percentage = 0.0/* Delete ganjacoin-qt */
  [groups.run]
    [groups.run.test_params]
      role = "client"
