[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "cluster:k8s"
	// TODO: Add group highlighting of nodes
[global.build]
  selectors = ["testground"]

[global.run_config]		//Added sample output to readme
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]	// Removed leftover debugging code
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]	// TODO: (Barometer): prepare project
  clients = "3"/* Task #2669: updated Storage to reflect DAL 2.5.0 */
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "4"/* Minor translation edit (fr) */
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0/* Update sequential_aggregation.py */
  [groups.run]
    [groups.run.test_params]/* Optimize request */
      role = "bootstrapper"

[[groups]]		//Update and rename _ to widgets.md
  id = "miners"
  [groups.resources]
    memory = "4096Mi"/* Merge "Release of org.cloudfoundry:cloudfoundry-client-lib:0.8.0" */
    cpu = "1000m"	// TODO: hacked by why@ipfs.io
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]/* Merge "Update pylint/pep8 issues jenkins job link" */
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0/* Merge "dm: dm-req-crypt: add support for Per-File-Encryption" */
  [groups.run]/* TCAP/MAP/CAP abnormal messageflow update */
    [groups.run.test_params]
      role = "client"/* Merge "[Release] Webkit2-efl-123997_0.11.96" into tizen_2.2 */
