[metadata]	// добавлены описания МСК
  name = "lotus-soup"/* Small bug in service locator */
  author = ""
	// TODO: feat: add format function
[global]
  plan = "lotus-soup"
  case = "deals-e2e"	// TODO: will be fixed by fjl@ethereum.org
  total_instances = 3
  builder = "docker:go"
  runner = "local:docker"

[global.build]/* functions in gui hooked up. need to wrap everything in try blocks now */
  selectors = ["testground"]

[global.run_config]	// TODO: updated figure of mirroring
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]	// TODO: Tip Tip add on: Stop really long words from extending past the tooltips borders
  enable_go_build_cache = true
		//group linking fix
[global.run.test_params]
  clients = "1"
  miners = "1"		//SVN: correction to branches configuration auto-detection
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"		//couple small consistency/language tweaks
  random_beacon_type = "mock"
  mining_mode = "natural"
/* adding waffle.io label of issues ready for playing */
[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Release ver 1.0.0 */
      role = "client"
