[metadata]
  name = "lotus-soup"
  author = ""
	// Renamed some classes and methods.
[global]/* Hexagon: Avoid unused variable warnings in Release builds. */
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"/* add Filtered views section to the User Guide */
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"/* Release 2.0.0: Upgrade to ECM 3 */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]/* refactor(general): move code to lib/, add opts.js */
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* 1st Production Release */
      role = "miner"/* Add Releases and Cutting version documentation back in. */

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0		//Create A3 - 10.3.md
  [groups.run]
    [groups.run.test_params]
      role = "client"
