[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"		//Update letters.py
  case = "deals-e2e"
  total_instances = 3
  builder = "docker:go"/* Release v0.5.7 */
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true/* 8b65b4c2-2e4b-11e5-9284-b827eb9e62be */

[global.run.test_params]
  clients = "1"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* Update Changelog to point to GH Releases */
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]	// TODO: casually drawing nn
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
