[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"	// TODO: will be fixed by xiemengjun@gmail.com

[global.build]/* Fixed Bug for Viewport Re-Projection */
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "5"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "5"
  random_beacon_type = "mock"/* Merge "[Release] Webkit2-efl-123997_0.11.112" into tizen_2.2 */
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"/* Release 10. */
  [groups.instances]
    count = 1	// TODO: Added a contribution guide (#163)
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"/* Merge "msm_fb: Release semaphore when display Unblank fails" */

[[groups]]
  id = "miners"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
		//Priority N tasks now get nextAction: true
[[groups]]
  id = "clients"
  [groups.instances]		//remove old queue
    count = 5
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
