[metadata]
  name = "lotus-soup"
  author = ""	// f8a4e4ae-2e4b-11e5-9284-b827eb9e62be

[global]
  plan = "lotus-soup"
  case = "deals-e2e"/* Merge "Destroy all contexts when render thread exits" into studio-1.2-dev */
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true/* Extracting dot generation logic to the helper */

[global.run.test_params]
  clients = "5"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "5"
  random_beacon_type = "mock"
  mining_mode = "natural"
	// recovery_backend: Set the genisoimage call to nonblocking on Popen.
[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
/* (vila) Release 2.4.0 (Vincent Ladeuil) */
[[groups]]
  id = "miners"/* update artCL */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]/* Updating build-info/dotnet/corefx/release/3.0 for rc2.19460.1 */
  id = "clients"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
