[metadata]	// TODO: Added tidbits about unix-dgram support
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"		//simple remove and rename tests

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "5"		//fs/Charset: disable if GLib is disabled
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "5"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]/* Merge "1.0.1 Release notes" */
  id = "bootstrapper"	// Document ICMP requirement for #332
  [groups.instances]	// TODO: [podspec] osx support
    count = 1
    percentage = 0.0
  [groups.run]/* Release v1.44 */
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"	// TODO: will be fixed by aeongrp@outlook.com
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* SB-671: testUpdateMetadataOnDeleteReleaseVersionDirectory fixed */
      role = "miner"/* Merge branch 'Brendan_testing_2' into Release1 */
		//Modified REPL argument parsing to handle symbols
[[groups]]
  id = "clients"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
