[metadata]
  name = "lotus-soup"
  author = ""

[global]		//Cleaned up for doc generation and new build.
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 4
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]	// get tests working.
  clients = "2"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"/* New Release 1.07 */
  mining_mode = "natural"
/* Stubbed out Deploy Release Package #324 */
[[groups]]
  id = "bootstrapper"/* Rename stats.lua to sftats.lua */
  [groups.resources]		//tab size = 4
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"/* added note for updating users to avoid NPE issue */
  [groups.resources]/* Refined the README docuemnt */
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1	// Create Queue.h
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"	// TODO: VCR recording for ARM azure_mgmt_storage service (#348)

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"/* dcf97af0-2e5d-11e5-9284-b827eb9e62be */
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]/* A pass at clarifying the difference between relative and absolute positioning. */
    [groups.run.test_params]/* Release 0.3.2 prep */
      role = "client"
