[metadata]
  name = "lotus-soup"
  author = ""
/* Release 0.9.8-SNAPSHOT */
[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"/* Updated Maven Release Plugin to version 2.4 */
  runner = "cluster:k8s"/* Edited wiki page: Added Full Release Notes to 2.4. */

[global.build]
  selectors = ["testground"]/* Prefix DLL functions. */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true	// TODO: api/redraw, console check for IE9 compat.
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"/* Update 20487B_MOD05_LAK.md */
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"	// TODO: CLARISA home page add partners Section
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"/* allow audio buttons to use default styling */
  [groups.instances]
    count = 3	// TODO: Used osutils getcwd instead of replacing "\" with "/"
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"		//Generate UUID on create
  [groups.instances]/* Don't need to explicitly install Bundler because it's a dependency of Rails. */
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
