[metadata]
  name = "lotus-soup"
  author = ""		//-check invariant
	// TODO: will be fixed by vyzo@hackzen.org
[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// TODO: hacked by arachnid@notdot.net
	// added ascendants and descendants
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"	// TODO: Add libssl 0.9.8
  go_proxy_url="http://localhost:8081"/* Release 2.5 */
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "3"
  genesis_timestamp_offset = "0"/* ARIS 1.0 Released to App Store */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"/* show units of vertical crs in profile plot */

[[groups]]/* Release MailFlute-0.5.1 */
  id = "bootstrapper"	// Comment noting why there are 2 fewer tests on PY3
  [groups.resources]
    memory = "512Mi"/* Folder structure of biojava3 project adjusted to requirements of ReleaseManager. */
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]	// Update Marco_Teorico
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]/* some design sheets */
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]	// TODO: will be fixed by josharian@gmail.com
    [groups.run.test_params]	// TODO: hacked by yuvalalaluf@gmail.com
      role = "client"
