[metadata]
  name = "lotus-soup"		//380b7eda-2e49-11e5-9284-b827eb9e62be
  author = ""/* Updated the r-viridislite feedstock. */

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 4/* Merge "sync: signal pt before sync_timeline object gets destroyed" */
  builder = "docker:go"/* Default the rpmbuild to Release 1 */
  runner = "cluster:k8s"
/* b8d2420a-2eae-11e5-addd-7831c1d44c14 */
[global.build]
  selectors = ["testground"]
	// Create HttpResponse_write.cs
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"	// #28: add docs to :override-with
  registry_type="aws"
	// TODO: add CodeshipApi to karma.conf
[global.run.test_params]
  clients = "2"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]/* Update and rename dosname.h to LIB/dosname.h */
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0/* Accolade ouvrante au meme niveau que sélecteur CSS */
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
/* Merge "install-guide: add 'obs' only tag for an openSUSE specific note" */
[[groups]]
  id = "miners"		//d8b5a442-585a-11e5-b994-6c40088e03e4
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0		//fix(package): update wdio-cucumber-framework to version 2.1.0
  [groups.run]
    [groups.run.test_params]/* Update md5 */
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
