[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"/* add this back in */
  case = "deals-e2e"
  total_instances = 6
  builder = "exec:go"/* d036246c-2e4e-11e5-9284-b827eb9e62be */
  runner = "local:exec"/* Fix building of the Android port after introducing cartridge.info.[ch] */

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// added simlink to gitignore

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]/* Release the transform to prevent a leak. */
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000.5" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.instances]/* Release 5.0.2 */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"	// ROO-862: Change default logging level for DataNucleus provider

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
