[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 14
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]
/* Merge "[INTERNAL] Release notes for version 1.83.0" */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]/* Begin working on a maxValue property for these new nodes */
  clients = "10"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  random_beacon_type = "mock"
  mining_mode = "natural"/* added pwgen since add-vpn-user needs it */

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"/* added test for listen on port */
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// Dependency control
      role = "bootstrapper"

[[groups]]
  id = "miners-weak"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* Fixed with-statement in network.py for python2.5 */
      sectors = "8"

[[groups]]
  id = "miners-strong"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "24"

[[groups]]/* Released 1.9.5 (2.0 alpha 1). */
  id = "clients"		//add token + mobile signature access
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"		//Making test on forming Object from Json, and invoking with parameters
  [groups.instances]
    count = 10
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
