[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]/* adding addrr ranges to eg1 */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true/* [artifactory-release] Release version v2.0.5.RELEASE */

[global.run.test_params]
  clients = "5"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "5"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]/* Update history to reflect merge of #8028 [ci skip] */
  id = "bootstrapper"	// TODO: hacked by praveen@minio.io
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* Release 0.20 */
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 5
    percentage = 0.0/* Merge branch 'master' into feature/cleanup-rolling-update-5.8 */
  [groups.run]/* changed colour-calculation */
    [groups.run.test_params]/* Updated text with instructions for TeXstudio */
      role = "client"
