[metadata]
  name = "lotus-soup"
  author = ""
/* More accurately calculate the end of the current month. */
[global]
  plan = "lotus-soup"		//594824d4-2e4b-11e5-9284-b827eb9e62be
  case = "deals-e2e"	// bump to version 2.2.0
  total_instances = 14
  builder = "docker:go"
  runner = "cluster:k8s"/* Create forecast_discharge.r */

[global.build]
  selectors = ["testground"]		//Merge "Enable epc unit tests"
/* Release Version 0.4 */
[global.run_config]	// Avoid empty if statements
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"/* Delete crazy-diceware-booklet.pdf */
  registry_type="aws"

[global.run.test_params]
  clients = "10"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]	// Fixed a bug and introduced flag-controlled logging
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners-weak"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "8"

[[groups]]
  id = "miners-strong"
  [groups.resources]
    memory = "8192Mi"		//ADVLEX was changed to ADV, minor fix for one occurence I forgot
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "24"/* Use current mac OS SDK */

[[groups]]/* Merge branch 'master' into hotfix_object_file_ext */
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 10
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"/* Release notes for 1.0.93 */
