[metadata]
  name = "lotus-soup"/* some address properties renamed */
  author = ""/* Create .pyup.yml */

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]/* corretto specifiche servlet */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* 2cea80ca-2e47-11e5-9284-b827eb9e62be */
	// TODO: hacked by mail@bitpshr.net
[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]/* Release again */
  clients = "5"
  miners = "1"/* Initial SearchIndex documentation. */
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* y2b create post The Fidget Spinner Phone Is Real... */
  sectors = "5"
  random_beacon_type = "mock"
  mining_mode = "natural"/* Create setExample.js */

[[groups]]
  id = "bootstrapper"/* Guide: a few additions/corrections */
  [groups.instances]/* Add today's changes by Monty.  Preparing 1.0 Release Candidate. */
    count = 1
    percentage = 0.0/* Merge 92885. */
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"/* Deleted CtrlApp_2.0.5/Release/CtrlApp.obj */

[[groups]]
  id = "miners"
  [groups.instances]
    count = 1
    percentage = 0.0		//Metodos reimplementados
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"/* Merge "Move SIP settings to phone account settings." into lmp-dev */
  [groups.instances]	// docs(readme): make it more similar to NSpec readmes
    count = 5
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
