[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"
	// TODO: hacked by arachnid@notdot.net
[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "4"
  random_beacon_type = "mock"	// TODO: Create LowerBound_UpperBound.cpp
  mining_mode = "natural"/* Release 2.0.5 plugin Eclipse */

[[groups]]
  id = "bootstrapper"
  [groups.resources]		//visual studio ignore
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]/* Merge "Release notes for "Disable JavaScript for MSIE6 users"" */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]/* Update README to point changelog to Releases page */
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: Memory leak: clear m_maptextures
      role = "miner"/* Improve templates to make output more readable. */
/* Release 0.6.0 of PyFoam */
[[groups]]		//4d931740-2e4e-11e5-9284-b827eb9e62be
  id = "clients"
  [groups.resources]
    memory = "1024Mi"	// TODO: will be fixed by steven@stebalien.com
    cpu = "1000m"
  [groups.instances]		//Require 'plugin_manager' in lib/jekyll.rb
    count = 3/* practica mysql y webapp */
    percentage = 0.0/* Added PopSugar Release v3 */
  [groups.run]
    [groups.run.test_params]
      role = "client"
