[metadata]	// TODO: added to why school for nature
  name = "lotus-soup"
  author = ""

[global]	// upd - PHP version.
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 5
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]		//Add additional book
		//Update custom_header_block.info
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]/* add tool configuration / run configuration launcher files */
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"		//Delete photorec.ses

[global.run.test_params]
  clients = "3"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B	// TODO: - Updated links in js for apartment details: flag report and contact button
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"
	// Update iscreen.cpp
[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"		//Update PigmyBlue.cs
  [groups.instances]
    count = 1
    percentage = 0.0/* Ensure port passed to reactor is int */
  [groups.run]
    [groups.run.test_params]	// TODO: hacked by hugomrdias@gmail.com
      role = "bootstrapper"	// TODO: Delete flaskr.db

[[groups]]
  id = "miners"
]secruoser.spuorg[  
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]	// Update emessage.cpp
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Release 7.0 */
      role = "miner"		//Update retrieveRaas.sh

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
