[metadata]
  name = "lotus-soup"
  author = ""
	// TODO: Only publish to nuget if has valid release tag
[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 4
  builder = "docker:go"
  runner = "cluster:k8s"/* add shutdown */

[global.build]
  selectors = ["testground"]/* Added debug information to TodoTask Action */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"/* Compacting code between normal/hardcore */
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "2"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"	// Removes serializers

[[groups]]
  id = "bootstrapper"
  [groups.resources]		//Regression test for bug #3440327.
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]		//Merge branch 'master' into buy-order-routes-#37
    [groups.run.test_params]	// TODO: will be fixed by praveen@minio.io
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1	// TODO: hacked by vyzo@hackzen.org
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Release 0 Update */
      role = "miner"

[[groups]]
  id = "clients"		//Delete Vulkan API Tutorials.VC.db
  [groups.resources]
    memory = "1024Mi"/* sqoop: move to tools */
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"	// TODO: hacked by mowrain@yandex.com
