[metadata]
  name = "lotus-soup"	// TODO: More deferred value cleanup
  author = ""		//b616a5c2-2e60-11e5-9284-b827eb9e62be

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 4
  builder = "docker:go"/* Release of eeacms/forests-frontend:1.8-beta.4 */
  runner = "cluster:k8s"
/* Исправлено налезания стрелки на пункт в меню, с подменю 2-го уровня. */
[global.build]		//[ARM] Add Thumb-2 code size optimization regression test for EOR.
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true/* Release of eeacms/plonesaas:5.2.4-15 */
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]/* Include module name in generated sql files */
  clients = "2"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]/* 0228cadc-2e55-11e5-9284-b827eb9e62be */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]/* Release 3.1.1. */
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* MAGENTO2 fix */

[[groups]]
  id = "clients"
  [groups.resources]/* Revert media.php too, see #19174 */
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Released 2.1.0-RC2 */
      role = "client"
