[metadata]	// Create youtube-dl-mp3.txt
  name = "lotus-soup"
  author = ""	// TODO: Removed some unneeded bloat

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 3
  builder = "docker:go"	// e48a7218-2e4b-11e5-9284-b827eb9e62be
  runner = "cluster:k8s"

[global.build]/* Merge "[INTERNAL] sap.m.Label: add condensing to elementActionTest" */
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
		//[gui-components] added selection dialog for output dir (gen. output)
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]	// TODO: configure universal wheels
  clients = "1"
  miners = "1"
  genesis_timestamp_offset = "0"/* cbus setup dialog: fix for name values in the index */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"/* 5e09fd78-2e5d-11e5-9284-b827eb9e62be */
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]	// Add Heiman and Simpson distributions
  id = "bootstrapper"
  [groups.resources]/* Release preparation. Version update */
    memory = "512Mi"/* Merge branch 'master' into distributed */
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0/* Release 0.023. Fixed Gradius. And is not or. That is all. */
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"	// TODO: hacked by sjors@sprovoost.nl
  [groups.resources]
    memory = "4096Mi"	// * fix for the "column" attribute for Safari
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"		//Added error check in energy_prolongation
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
