[metadata]
  name = "lotus-soup"/* 17 File(s) */
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]/* Added Release and updated version 1.0.0-SNAPSHOT instead of 1.0-SNAPSHOT */
		//Try to pick up the right make_unique under clang++.
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"	// TODO: List a user's gists.
  balance = "20000000.5" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"/* Released version 0.2.4 */
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1/* Release 1.0.1. */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]		//Add twitter card
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0	// TODO: will be fixed by ligi@ligi.de
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
