[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 3
  builder = "docker:go"
  runner = "cluster:k8s"	// TODO: Fix for handling wrapped exceptions.

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* 73c6e5de-35c6-11e5-bcf4-6c40088e03e4 */
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"		//move around and clean up haddock comments
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]		//Create action-network.md
  clients = "1"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* Replace data with gzip versions */
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"	// TODO: Add unit PRice
    cpu = "1000m"		//Use Domain modeling for canonical setup
  [groups.instances]/* Released springrestclient version 2.5.9 */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"/* Release 0.1.1-dev. */
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
		//Merge "BUG: MaskOneImageGivenLabelMap test name for baseline comparison."
[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"	// Allow downloading from archive.eclipse.org
  [groups.instances]
    count = 1	// Fixed bug in parser, improved outlineItem further.
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
