[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 5
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* New version of CWP-YouIT - 1.1.0 */
[global.build_config]
  push_registry=true/* Pin pg8000 to latest version 1.10.6 */
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "1"
  genesis_timestamp_offset = "0"/* Released springjdbcdao version 1.7.14 */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
	// TODO: 260ee034-2e56-11e5-9284-b827eb9e62be
[[groups]]	// TODO: hacked by arajasek94@gmail.com
  id = "miners"/* 1st Draft of Release Backlog */
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
