[metadata]
  name = "lotus-soup"
  author = ""
		//Made installer more obvious
[global]
  plan = "lotus-soup"
  case = "deals-e2e"	// TODO: Create Pill_Bug_Lab.md
  total_instances = 7	// Update Get-CruftyWebFiles.ps1
  builder = "docker:go"
  runner = "cluster:k8s"		//Mise à jour I. curvipes
/* Update WorkflowScheduler.md */
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"/* Release 0.0.13 */

[global.run.test_params]
  clients = "3"/* Fixed: Hide VP8 Speed option for other codecs */
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]/* Update Release 0 */
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"	// TODO: will be fixed by cory@protocol.ai
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]		//Resized ClearButton
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Release 1.3.23 */
      role = "client"		//Update RESULT_GTX1080.md
