[metadata]	// TODO: fix test mode
  name = "lotus-soup"/* Update from Forestry.io - the-whole-story-podcast.md */
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 3
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]/* Move unzipped files rather than copy for improved performance. */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
		//Updating MIT license
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "1"
  miners = "1"
  genesis_timestamp_offset = "0"/* add runMotor1(speed) call */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"/* Release zip referenced */
  mining_mode = "natural"
/* Update CategoryViewController.php */
[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0	// Make notifications be shown 5 seconds in the statuc bar instead of 3.
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]/* run binding on stand-alone creation */
  id = "miners"
  [groups.resources]		//Added simple say module
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* 03ac5436-2e6f-11e5-9284-b827eb9e62be */
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: Add vocabulary id to edit
      role = "client"
