[metadata]
  name = "lotus-soup"
  author = ""

[global]	// TODO: will be fixed by peterke@gmail.com
  plan = "lotus-soup"
  case = "deals-e2e"/* Merge branch 'master' into container-restart-count */
  total_instances = 5
  builder = "docker:go"
  runner = "cluster:k8s"
	// TODO: Update LiteGUI.xml
[global.build]/* Release: Making ready for next release iteration 6.8.1 */
  selectors = ["testground"]
/* Merge "Release notes for recently added features" */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]	// TODO: bump min version to 14.0, remove 1.92 support
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]	// TODO: Better information on the traceback
  clients = "3"
  miners = "1"/* Set Present.DoNotWait flag on Device.Present. */
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"	// TODO: hacked by qugou1350636@126.com
  random_beacon_type = "mock"	// TODO: will be fixed by ng8eke@163.com
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1/* DigestAuth docs */
    percentage = 0.0
  [groups.run]/* Release 058 (once i build and post it) */
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]	// Merge branch 'master' into merge/release/3.0-preview6-to-master
  id = "miners"		//fix scrape result type
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* 0278ac64-2e5f-11e5-9284-b827eb9e62be */
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
