[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"/* Merge "Release caps lock by double tap on shift key" */
  total_instances = 6
  builder = "docker:go"	// add tooltipp css
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]	// TODO: Directory 'srcFraglich' removed

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"/* Release-1.3.4 : Changes.txt and init.py files updated. */
  registry_type="aws"
/* Release notes for v3.10. */
[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "4"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]		//remove /usr/bin/env ansible takes care of that
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: Merge "msm: platsmp: Release secondary cores of 8092 out of reset" into msm-3.4
      role = "client"	// TODO: TCC-20 Propagate needsScoring flag from inner query
