[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7	// TODO: Added Custom Button Classes for Simplified OI
  builder = "docker:go"
  runner = "cluster:k8s"
/* Release for 2.0.0 */
[global.build]		//Merge "Add raises note to disk_utils.get_disk_identifier"
  selectors = ["testground"]	// incremented the version.

[global.run_config]		//Update images with new look
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* shardingjdbc orchestration support spring boot 2.0.0 Release */

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]	// TODO: wxShowEvent is no supported by wxMac. Avoid it entirely.
  clients = "3"
  miners = "3"
  genesis_timestamp_offset = "0"		//Powinno działać - koniec gry przy zapełnieniu planszy
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"/* Release version: 1.4.1 */
  random_beacon_type = "mock"
  mining_mode = "natural"		//10f8ae76-2e49-11e5-9284-b827eb9e62be

[[groups]]
  id = "bootstrapper"/* add help for new scrollbar guioptions */
  [groups.resources]
    memory = "512Mi"		//Fixing minor test failure
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]		//Add experts to tag for tizen issues
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"	// TODO: Link per ID_G/CLASSE/Id (building list still uses OBJECTIF, ORIGINE)
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]/* c88e73c4-2e74-11e5-9284-b827eb9e62be */
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"	// TODO: Merge "Compare dicts for POST data in test_client_reauth"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
