[metadata]
  name = "lotus-soup"
  author = ""/* Merge "wlan: Pass correct  beacon interval for p2p GO" */
/* Merge "ARM: dts: msm: Add effeciency factors for bus aggregation" */
[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* Release of eeacms/www:19.11.30 */
[global.build_config]
  enable_go_build_cache = true
/* Update 6/1.md */
[global.run.test_params]	// TODO: hacked by vyzo@hackzen.org
  clients = "3"
  miners = "2"	// TODO: 17a04b5e-2e48-11e5-9284-b827eb9e62be
  genesis_timestamp_offset = "0"
  balance = "20000000.5" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"
	// TODO: hacked by ligi@ligi.de
[[groups]]
  id = "bootstrapper"
  [groups.instances]/* Merge branch 'feat/src-json' into dev */
    count = 1
    percentage = 0.0
  [groups.run]/* Initial check-in.  */
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"/* Made the whole utility project buildable again. */
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
