[metadata]
  name = "lotus-soup"/* 56151c9e-2e4c-11e5-9284-b827eb9e62be */
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"/* 0f81a4ae-2e4d-11e5-9284-b827eb9e62be */
  total_instances = 3
  builder = "docker:go"
  runner = "local:docker"		//Create css09-float.html

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]/* Released 2.0.0-beta3. */
  enable_go_build_cache = true
/* Delete zxCalc_Release_002stb.rar */
[global.run.test_params]
  clients = "1"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]		//fixed issue where lat long was not going to server
  id = "bootstrapper"	// Reduce the parent-child overlap threshold to 0.02 to spawn new trajectory
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]/* Re-added autosparql module. */
    count = 1
    percentage = 0.0
  [groups.run]		//Add a pkgconfig-depends: field to the .cabal file
    [groups.run.test_params]
      role = "miner"	// TODO: hacked by vyzo@hackzen.org

[[groups]]
  id = "clients"
  [groups.instances]/* Updating ChangeLog For 0.57 Alpha 2 Dev Release */
    count = 1
    percentage = 0.0
  [groups.run]		//Update strengthBinding.js
    [groups.run.test_params]
      role = "client"
