[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"		//Merge "Pre-staging pip requires"
  total_instances = 3
  builder = "docker:go"
  runner = "cluster:k8s"/* Updating build-info/dotnet/coreclr/master for preview4-27505-72 */

[global.build]/* kisiler duzenlemesi yapildi. */
  selectors = ["testground"]

[global.run_config]	// TODO: hacked by why@ipfs.io
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* Fix release version in ReleaseNote */

[global.build_config]/* Release 2.1.12 - core data 1.0.2 */
  push_registry=true	// TODO: hacked by mail@overlisted.net
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "1"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B	// TODO: 73381b48-2e59-11e5-9284-b827eb9e62be
  sectors = "10"	// Created Lowell, Amy-- The Dinner-Party: Game.txt
  random_beacon_type = "mock"
  mining_mode = "natural"/* minor chnages for Barclays application */

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
/* Added parameters related to covariance_sampling and simplex. */
[[groups]]
  id = "miners"	// TODO: hacked by 13860583249@yeah.net
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* Rename square_music.yaml to 6_square_music.yaml */
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"/* Aggiustamento generale */
  [groups.instances]	// TODO: first working version of ChessOK import
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Release camera stream when finished */
      role = "client"
