[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"	// fixed x64 compilation error
  total_instances = 6
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]
/* Release for 18.22.0 */
[global.run_config]/* Release 1.0 code freeze. */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* some kind of timing and parsing.. can render something already */

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]/* Release of eeacms/ims-frontend:0.3.4 */
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000.5" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"/* check_signature, get_satus_output and Dict move to utils */
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.instances]/* Add ResultPersistence execute methods */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"		//Updating build-info/dotnet/coreclr/master for beta-25012-01
  [groups.instances]
    count = 2		//Fix bad path is Travis Badges.
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* firewall: do not process rules in reverse */
      role = "client"
