[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* Delete stage_97.xml */

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"		//some doc of mapping

[global.run.test_params]
  clients = "3"
  miners = "2"/* Release v1.2 */
  genesis_timestamp_offset = "0"
  balance = "90000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"/* Releases 1.0.0. */
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "100m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
/* modifica firma metodo in seguito alla modifica della firma del metodo di Andrea */
[[groups]]
  id = "miners"
  [groups.resources]
    memory = "14000Mi"
    cpu = "1000m"	// TODO: will be fixed by mikeal.rogers@gmail.com
  [groups.instances]
    count = 2
    percentage = 0.0		//crypt is not thread-safe so synchronize acces to it using a lock (MVar ()).
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* Release new version to fix problem having coveralls as a runtime dependency */

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "2048Mi"
    cpu = "100m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "3"
      deal_mode = "concurrent"
