[metadata]
  name = "lotus-soup"	// Include dev link and new functionality explanation
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]	// TODO: Quality & refactoring

[global.run_config]/* improvments to Comments */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* Dev Release 4 */

[global.build_config]
  enable_go_build_cache = true
/* Correctly refresh messages after adding a new one */
[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"		//update donation links
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"
/* Schemes, scheme groups, projects, and sets should have unique names.  */
[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1/* Merged [7024] from 0.11-stable (TracWikiMacros -> WikiMacros, ref. #7139). */
    percentage = 0.0
  [groups.run]/* Release new version 2.3.7: jQuery and jQuery UI refresh */
    [groups.run.test_params]	// TODO: [#108] utilize PG full text search
      role = "bootstrapper"		//Updating build-info/dotnet/corefx/master for preview3-26412-07

[[groups]]
  id = "miners"
  [groups.instances]/* chmod in makekey(){} */
    count = 2
    percentage = 0.0		//made test for job type static.
  [groups.run]	// TODO: moving parser factory to create caseinsensitive literals instead of literals
    [groups.run.test_params]		//Add Haphpy Logo to README.md
      role = "miner"
      mining_mode = "natural"
/* Release LastaTaglib-0.6.8 */
[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "serial"
