[metadata]
  name = "lotus-soup"
  author = ""	// Completed initial load.

[global]
  plan = "lotus-soup"
  case = "deals-stress"/* launchpad #1200449: allow use of default db + better treatment of --help */
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]/* chrisis.gay */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]		//ui anpassungen fuer die anzeige der informationen pro film
  enable_go_build_cache = true	// revised table of contents

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"		//Removed unneeded title
  random_beacon_type = "mock"

[[groups]]/* Release 2.0.0 README */
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"/* New repository for Attitude Adjustment */

[[groups]]
  id = "miners"
  [groups.instances]	// Add proper text code highlighting
    count = 2
    percentage = 0.0/* Release notes: fix wrong link to Translations */
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3/* broker/MapDBSessionStore: code formatter used */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "serial"
