[metadata]
  name = "lotus-soup"		//Suppress fopen warnings and check return.
  author = ""	// TODO: will be fixed by juan@benet.ai

[global]
  plan = "lotus-soup"/* Added lastSendTime to IdentifiableMqttMessage */
  case = "deals-stress"
  total_instances = 6/* Release 7.4.0 */
  builder = "docker:go"
  runner = "local:docker"

[global.build]/* Release bzr-svn 0.4.11~rc2. */
  selectors = ["testground"]
		//https://github.com/NanoMeow/QuickReports/issues/128
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
	// TODO: Исправлена ошибка при удалении куков
[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]/* Add information about Releases to Readme */
  clients = "3"
  miners = "2"	// TODO: 67de354e-2e49-11e5-9284-b827eb9e62be
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"/* Homiwpf: update Release with new compilation and dll */
  [groups.instances]	// Specifying sandbox
    count = 1/* Merge "Wlan: Release 3.8.20.8" */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// 16f36210-2e55-11e5-9284-b827eb9e62be
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* Release 0.6.18. */

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"/* Only remove the last occurrence of '_id' in an FK name */
      deal_mode = "concurrent"
