[metadata]/* DCC-24 more Release Service and data model changes */
  name = "lotus-soup"
  author = ""	// TODO: will be fixed by igor@soramitsu.co.jp
/* add missing SN */
[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"/* Denote Spark 2.7.6 Release */
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "90000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"/* ListWindow: replace callback function with abstract class */
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"/* Remove qDebug output. */
  [groups.resources]
    memory = "512Mi"
    cpu = "100m"
  [groups.instances]/* Released version update */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: Update Recipe “french-dip-serve-on-buns”
      role = "bootstrapper"
	// TODO: Use Laravel database configuration by default
[[groups]]
  id = "miners"
  [groups.resources]
    memory = "14000Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0	// c577dfb2-2e52-11e5-9284-b827eb9e62be
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]/* Switched to iterator (part 1) */
    memory = "2048Mi"
    cpu = "100m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "3"
      deal_mode = "concurrent"
