[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]	// TODO: hacked by alessio@tendermint.com
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"		//Change aspect ratio of header

[global.run.test_params]
  clients = "3"
  miners = "2"		//Create PVP flag alliance
  genesis_timestamp_offset = "0"
  balance = "90000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* Release version 4.0.0.M1 */
  sectors = "10"
  random_beacon_type = "mock"		//diff rotation
  mining_mode = "natural"/* .......... [ZBXNEXT-686] updated information for auditlog tests */

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "100m"
  [groups.instances]
    count = 1/* time: Add date in x86-debug and x86-pnet templates */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "14000Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2	// TODO: Add assembleDist for Android projects
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* fix messagessend  more beautifull */

[[groups]]	// 3b55295c-2e61-11e5-9284-b827eb9e62be
  id = "clients"
  [groups.resources]
    memory = "2048Mi"
    cpu = "100m"		//2nd edit by Mehadi.
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"/* Distinguish between classes and interfaces */
      deals = "3"
      deal_mode = "concurrent"
