[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6		//Update spa-sms.md
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]/* New version of ForeverWood - 1.0.4 */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* Rename autologon.py to raffle/autologon.py */
[global.build_config]/* Added more UX links */
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "2"/* done waiting for a staff meet to start */
  genesis_timestamp_offset = "0"
  balance = "90000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"		//forward block only if received unsolicited
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "100m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"	// TODO: hacked by brosner@gmail.com

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "14000Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "2048Mi"
    cpu = "100m"
  [groups.instances]
    count = 3		//Cherry pick measure example
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "3"
      deal_mode = "concurrent"
