[metadata]		//[IMP] google_docs : changes for tooltip of filter
  name = "lotus-soup"/* Merge branch 'master' into py39 */
  author = ""
		//800cbfd4-2e47-11e5-9284-b827eb9e62be
[global]
  plan = "lotus-soup"
  case = "deals-stress"/* Make maxy/y final */
  total_instances = 6/* Released DirectiveRecord v0.1.31 */
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true	// Update 10_hashes.rb

[global.run.test_params]
  clients = "3"/* Unused variable warning fixes in Release builds. */
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"/* [#1228] Release notes v1.8.4 */

[[groups]]
  id = "bootstrapper"		//[bouqueau] fix mpd lock on failure
  [groups.instances]/* Released V1.0.0 */
    count = 1/* Added image of Rice Typewriter */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Merge "board: msm8x60: stabilize vregs on resume" into android-msm-2.6.35 */
      role = "bootstrapper"

[[groups]]
  id = "miners"		//208ddc47-2e9c-11e5-9e34-a45e60cdfd11
  [groups.instances]
    count = 2
    percentage = 0.0/* Exposing hMethod. */
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* Add .bash_history private dotfile to Mackup. */
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
