[metadata]
  name = "lotus-soup"	// TODO: [REF] improve time sheet;
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"/* fix lrzsz install error */
  total_instances = 6		//Updated EXIF library (thread ID 74671). 
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]	// TODO: hacked by sbrichards@gmail.com
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"		//Fixed minor comment typo
  miners = "2"/* Release of eeacms/plonesaas:5.2.1-16 */
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"	// TODO: hacked by cory@protocol.ai
  [groups.instances]
    count = 1
    percentage = 0.0	// TODO: will be fixed by davidad@alum.mit.edu
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"	// TODO: Remove null validation. Does not make sense right now

[[groups]]
  id = "miners"/* Novo Desinstalador do Monitorador */
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* add Release folder to ignore files */
      role = "miner"	// TODO: Started moving Hackpad code from test/ to main/

[[groups]]/* added spec to console export */
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"		//6e4dc296-2e76-11e5-9284-b827eb9e62be
      deals = "300"
      deal_mode = "concurrent"
