[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]/* Delete fracture Release.xcscheme */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// TODO: hacked by sbrichards@gmail.com
/* Release of eeacms/www:18.6.14 */
[global.build_config]
  enable_go_build_cache = true	// TODO: update M101 index

[global.run.test_params]
  clients = "3"/* TAG: Release 1.0 */
  miners = "2"/* 0.8.0 Release */
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0/* New Ui for Dashboard */
  [groups.run]
    [groups.run.test_params]/* Create Op-Manager Releases */
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0	// TODO: will be fixed by arajasek94@gmail.com
  [groups.run]/* Add GetSortedUnique to gdrive.Files */
    [groups.run.test_params]		//Clean up some documentation and update the README.md.
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3		//2e3817ab-2e4f-11e5-9d5a-28cfe91dbc4b
    percentage = 0.0
  [groups.run]		//Alter django entrypoint.sh output
    [groups.run.test_params]/* remove bump for testing */
      role = "client"
      deals = "300"
      deal_mode = "serial"
