[metadata]		//Create rust.yml
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"/* 1.1.5o-SNAPSHOT Released */
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"	// TODO: we can list properly
  runner = "local:docker"
/* Release 1.0.0-rc0 */
[global.build]		//Merge "Avoid ConcurrentModificationException on providers"
  selectors = ["testground"]

[global.run_config]	// TODO: hacked by magik6k@gmail.com
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* 4d77ceec-2e42-11e5-9284-b827eb9e62be */

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]	// Corrected `crn tree` description
  clients = "3"
  miners = "2"/* Release a hotfix to npm (v2.1.1) */
  genesis_timestamp_offset = "0"		//[release] prepare for next development iteration
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* add HIve Conf */
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0/* Add -R/--output-fw-rules flag and lint fixes */
  [groups.run]/* Update PALMPMPT.txt */
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]	// netloan-webapp ChangeCSS
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
