[metadata]	// d0cf3078-2e65-11e5-9284-b827eb9e62be
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6	// TODO: will be fixed by davidad@alum.mit.edu
  builder = "docker:go"/* Task #8399: FInal merge of changes in Release 2.13 branch into trunk */
  runner = "local:docker"
/* Release Notes: NCSA helper algorithm limits */
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// Changelog wording

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]/* Merge branch 'development' into 789-benchmark_nacl */
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"		//The InstallAllGenerator
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0		//meta code generator wrapper script
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]/* Intento de bugfix en las validaciones. */
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]/* less verbose logging in Release */
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0/* Update Release Planning */
  [groups.run]
    [groups.run.test_params]/* test json round trip */
      role = "client"
      deals = "300"		//us.messages.txt : fix some text (SF bug 1601477)
      deal_mode = "serial"
