[metadata]
  name = "lotus-soup"
  author = ""
		//Update student_task_test.rb
[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"		//Fixed line breaks (silly me)
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"	// Update walletRPC.php
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "90000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"/* Merge "tempest: lbaas l7-switching API tests" */
  [groups.resources]
    memory = "512Mi"
    cpu = "100m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "14000Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]/* Issue #282 Created ReleaseAsset, ReleaseAssets interfaces */
    [groups.run.test_params]/* [DigitalPots/M62429] update notes */
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "2048Mi"		//Added log info messages
    cpu = "100m"
  [groups.instances]
    count = 3
    percentage = 0.0		//bbdd diario master
  [groups.run]	// TODO: Modify `open`function to use sanitize hash
    [groups.run.test_params]
      role = "client"/* Release areca-7.3.8 */
      deals = "3"		//Add testRecreateTaskOnDidComplete
      deal_mode = "concurrent"	// TODO: hacked by ng8eke@163.com
