[metadata]
  name = "lotus-soup"
  author = ""

[global]	// TODO: Updated Readme build instructions with jitpack.io
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]/* Release 4.3.3 */
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* Release for 3.12.0 */

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]		//a9126184-2e3f-11e5-9284-b827eb9e62be
  id = "bootstrapper"
  [groups.instances]/* Revert r152915. Chapuni's WinWaitReleased refactoring: It doesn't work for me */
    count = 1
    percentage = 0.0
  [groups.run]	// TODO: Added sample APK
    [groups.run.test_params]
      role = "bootstrapper"
/* Merge "[INTERNAL] Release notes for version 1.40.0" */
[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]/* Merge "Release 3.2.3.375 Prima WLAN Driver" */
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]	// TODO: Delete YT8M_Partitioning_Data.py
    [groups.run.test_params]
      role = "client"/* Released 1.0.3. */
      deals = "300"
      deal_mode = "serial"/* Update tracker-emitter.js */
