[metadata]
  name = "lotus-soup"/* Version 0.2 Release */
  author = ""

[global]
  plan = "lotus-soup"/* Generated site for typescript-generator-core 1.5.158 */
  case = "deals-stress"
  total_instances = 6	// TODO: hacked by steven@stebalien.com
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* 8b332571-2d14-11e5-af21-0401358ea401 */
[global.build_config]/* Create formations */
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"
/* Release 0.4.0.4 */
[[groups]]		//Merged development into deploy
  id = "bootstrapper"
  [groups.instances]/* README mit Link zu Release aktualisiert. */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"/* Fix number location computation. */

[[groups]]
  id = "miners"
  [groups.instances]/* remove reference drawings in MiniRelease2 */
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"/* Update and rename prob4.m to prob4a.m */

[[groups]]/* Implement property getter/setter */
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
