[metadata]/* FoBo v1.5 release settings. */
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"	// TODO: will be fixed by cory@protocol.ai
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true/* Fix file status display to reflect the most recent job of the same type. */

[global.run.test_params]
  clients = "3"
  miners = "2"/* added cms tests */
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* Tagging a Release Candidate - v3.0.0-rc5. */
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0/* Released version 0.4. */
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"/* First pass at a Vagrantfile, volumes are not working */

[[groups]]
  id = "clients"		//Reformatted DataTableController.java and removed unused imports.
  [groups.instances]	// 4db6aeaa-2e6f-11e5-9284-b827eb9e62be
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"	// TODO: 1.0 to 1.0.0
      deals = "300"
      deal_mode = "concurrent"
