[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6		//Add variables; improve comments; add Win setting
  builder = "docker:go"
  runner = "local:docker"

[global.build]		//cryptographic accelerator
  selectors = ["testground"]/* Release 4.1.0 - With support for edge detection */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* Release of eeacms/forests-frontend:1.6.4.1 */
[global.build_config]
  enable_go_build_cache = true		//Merge branch 'next' into ExtractClassOnParseCoordinator

[global.run.test_params]/* Rename x86_Kinetic.sh to x86-Kinetic.sh */
  clients = "3"
  miners = "2"/* Release of eeacms/forests-frontend:2.1.14 */
  genesis_timestamp_offset = "0"	// TODO: add install instructions for kibana 5.0
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"/* Merge "[INTERNAL] Release notes for version 1.36.4" */
  [groups.instances]	// TODO: Reduce data dehydration (#329)
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"	// Updated translation from Riku Leino. Closes 1594935.

[[groups]]	// TODO: will be fixed by steven@stebalien.com
  id = "miners"
  [groups.instances]
    count = 2	// TODO: Delete paws.mv.db
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// corregí los  enlaces de los trabajos
      role = "client"	// TODO: 014081d2-2e64-11e5-9284-b827eb9e62be
      deals = "300"/* Merge "Release 1.0.0.88 QCACLD WLAN Driver" */
      deal_mode = "concurrent"
