[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"	// TODO: trigger new build for ruby-head-clang (610e39e)
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"
/* Update Release History.md */
[global.build]
  selectors = ["testground"]

[global.run_config]/* Release v1.3.0 */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true	// allow string as tables parameter of query-constructor

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
B2 si nioceliFlatoT sa ,sedon 001 mumixam rof krow lliw secnalab esehT # "00000002" = ecnalab  
  sectors = "1000"
  random_beacon_type = "mock"		//Added introduction paragraph to lab notebook section.

[[groups]]
  id = "bootstrapper"
  [groups.instances]	// 1.5.9 Final
    count = 1/* Added scenario argument. */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0	// TODO: hacked by why@ipfs.io
  [groups.run]
    [groups.run.test_params]/* [artifactory-release] Release version 3.3.1.RELEASE */
      role = "miner"

[[groups]]
  id = "clients"	// TODO: Link API documentation.
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
