[metadata]
  name = "lotus-soup"
  author = ""
/* Envoi de SMS opérationel */
[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"/* Release 2.2.0 */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"
/* Release 1.1.4 preparation */
[[groups]]
  id = "bootstrapper"/* Release fixes */
  [groups.instances]/* Allow invoking SynergyService with less detail. */
    count = 1
    percentage = 0.0
  [groups.run]/* add disclaimer :boom: */
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"/* Release areca-7.2.14 */
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]	// TODO: upload input files required to run 2d btest
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]	// Created vagrant berkshelf (markdown)
  id = "clients"		//ac0883ec-2e3e-11e5-9284-b827eb9e62be
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
