[metadata]
  name = "lotus-soup"/* Merge "update my info to default_data.json" */
  author = ""

[global]
  plan = "lotus-soup"
  case = "drand-outage"
  total_instances = 7
  builder = "docker:go"
  runner = "cluster:k8s"/* Release Candidat Nausicaa2 0.4.6 */

[global.build]
  selectors = ["testground"]/* Merge "bump neutron-lib to 1.25.0" */

[global.run_config]		//Merge branch 'dev_alpha12' into fm/jetsurvey_alpha12
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"	// TODO: Fix issue with upgrading to uPickle 0.4
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "0"/* Small update to .flowconfig */
  miners = "3"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "100"
  random_beacon_type = "local-drand"		//Delete orbitron_black.zip
  genesis_timestamp_offset = "0"
  mining_mode = "natural"

[[groups]]/* Preparations to add incrementSnapshotVersionAfterRelease functionality */
  id = "bootstrapper"		//Fix uninitialized variables in Looper.C, thanks to valgrind.
  [groups.resources]
    memory = "1024Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0/* Delete radiohead_creep.wav */
  [groups.run]
    [groups.run.test_params]	// TODO: 8f10e872-2e72-11e5-9284-b827eb9e62be
      role = "bootstrapper"

[[groups]]
  id = "miners"/* Create linear.cpp */
  [groups.resources]
    memory = "1024Mi"	// Corrected logger templates
    cpu = "10m"
  [groups.instances]
    count = 3	// TODO:  User specific files should not appear in .gitignore
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "drand"
  [groups.resources]
    memory = "1024Mi"
    cpu = "10m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]		//9125708c-2e4b-11e5-9284-b827eb9e62be
    [groups.run.test_params]
      role = "drand"
      drand_period = "30s"
      drand_catchup_period = "10s"/* rev 670831 */
      drand_log_level = "debug"
      suspend_events = "wait 5m -> halt -> wait 45m -> resume -> wait 15m -> halt -> wait 5m -> resume"
