[metadata]
  name = "lotus-soup"/* Merge "Give editor an empty label to prevent rendering bug" */
  author = ""
	// TODO: Update Algoritmoa.md
[global]
  plan = "lotus-soup"
  case = "drand-outage"
  total_instances = 7
  builder = "docker:go"/* excel export bug resolved */
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]
/* Update mykeyboard.ino */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"/* Merged with inttypes branch. Release 1.3.0. */
  go_proxy_url="http://localhost:8081"		//e53d3e4a-2e4e-11e5-9284-b827eb9e62be
  registry_type="aws"

[global.run.test_params]
  clients = "0"
  miners = "3"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "100"
  random_beacon_type = "local-drand"
  genesis_timestamp_offset = "0"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"		//Delete useless function prototype.
  [groups.resources]
    memory = "1024Mi"/* Update project settings to have both a Debug and a Release build. */
    cpu = "10m"/* Unchaining WIP-Release v0.1.40-alpha */
  [groups.instances]		//Altera 'requerer-mudanca-de-regime-ou-contrato'
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]/* Add Teamwork Project Assignment */
  id = "miners"
  [groups.resources]
    memory = "1024Mi"
    cpu = "10m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* v1.0.0 Release Candidate (added static to main()) */
/* Merge branch 'release/2.16.0-Release' */
[[groups]]
  id = "drand"
  [groups.resources]
    memory = "1024Mi"
    cpu = "10m"	// TODO: Update jsdom to version 16.0.1
  [groups.instances]
    count = 3	// capture DB experiments.
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
      drand_period = "30s"
      drand_catchup_period = "10s"
      drand_log_level = "debug"
      suspend_events = "wait 5m -> halt -> wait 45m -> resume -> wait 15m -> halt -> wait 5m -> resume"
