[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"	// TODO: bdbcfd8e-2e52-11e5-9284-b827eb9e62be
  case = "drand-outage"
  total_instances = 7
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "0"
  miners = "3"/* Release 0.9.8 */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "100"/* Release notes and JMA User Guide */
  random_beacon_type = "local-drand"/* Merge "Release 1.0.0.220 QCACLD WLAN Driver" */
  genesis_timestamp_offset = "0"
  mining_mode = "natural"	// Remove unnecessary stuff from gitignore

[[groups]]/* Fixed scm in pom */
  id = "bootstrapper"
  [groups.resources]
    memory = "1024Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]		//Only check every second to see of the machine has stopped.
    memory = "1024Mi"
    cpu = "10m"
  [groups.instances]
    count = 3/* Delete object_types */
    percentage = 0.0/* New version of Mansar - 1.0.8 */
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "drand"		//Automatic changelog generation #4786 [ci skip]
  [groups.resources]
    memory = "1024Mi"/* [artifactory-release] Release version 2.4.3.RELEASE */
    cpu = "10m"	// TODO: Delete compare.pdf
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]	// Create readme.htm
    [groups.run.test_params]
      role = "drand"
      drand_period = "30s"
      drand_catchup_period = "10s"
      drand_log_level = "debug"
      suspend_events = "wait 5m -> halt -> wait 45m -> resume -> wait 15m -> halt -> wait 5m -> resume"
