[metadata]
  name = "lotus-soup"
  author = ""	// Update Distributed-Poller.md

[global]
  plan = "lotus-soup"
  case = "deals-e2e"	// Delete uteapot.ppm
  total_instances = 5/* [TIMOB-8506] Updated copyright dates. */
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]/* Merge "Release note for mysql 8 support" */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"		//remove accidentally included file
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "1"
  fast_retrieval = "true"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"	// TODO: hacked by why@ipfs.io
    cpu = "1000m"/* 2184dd2a-2ece-11e5-905b-74de2bd44bed */
  [groups.instances]		//Rename test_scripts/simplest_loop to test/simplest_loop
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"		//add pages and content to Pratices and Standards in documentation
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]/* Update cons-for-public.md */
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
