[metadata]
  name = "lotus-soup"
  author = ""/* Refactored Tree and HashTree */

[global]/* removed all the extra whitespace */
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 5
  builder = "docker:go"
  runner = "cluster:k8s"	// TODO: hacked by hello@brooklynzelenka.com

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "1"
  fast_retrieval = "true"
  genesis_timestamp_offset = "0"/* Add support to use Xcode 12.2 Release Candidate */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B		//Supressed warnings imported from mysql-5.5
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]	// TODO: will be fixed by nicksavers@gmail.com
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"/* Merge "wlan: Release 3.2.4.101" */
    cpu = "1000m"
  [groups.instances]	// TODO: hacked by davidad@alum.mit.edu
    count = 1
    percentage = 0.0
  [groups.run]	// TODO: will be fixed by xiemengjun@gmail.com
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"/* Minor fixes - maintain 1.98 Release number */
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
