[metadata]
  name = "lotus-soup"
  author = ""
/* Release 0.9.1.7 */
[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 5
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]	// TODO: hacked by peterke@gmail.com
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* Delete smallseotools-1503847728.pdf */
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]/* Merge branch 'master' into python3-only */
  clients = "3"/* 0d5fef9e-2e59-11e5-9284-b827eb9e62be */
  miners = "1"
  fast_retrieval = "true"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]/* Release notes for the extension version 1.6 */
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0	// TODO: Update highlighter.cpp
  [groups.run]/* 492ee5ac-2e4f-11e5-9284-b827eb9e62be */
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"		//max_backlog_multiplier typo
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"	// TODO: Make it so displayed values changed depending on measurement type settings.
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]/* Added try\catch for new Exceptions */
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
