[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 5/* increase max_execution_time and file upload size */
  builder = "docker:go"
  runner = "cluster:k8s"	// Update class-01-resolved-felipehfs-Felipe Henrique.md

[global.build]
  selectors = ["testground"]

[global.run_config]		//Update Stack_Template.cpp
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]	// TODO: hacked by nick@perfectabstractions.com
  clients = "3"
  miners = "1"
  fast_retrieval = "true"/* Merge "Release 3.2.3.306 prima WLAN Driver" */
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"		//Create python para zumbis - lista 3
  mining_mode = "natural"
	// Fixed README.md for @tbielawa closing #10.
[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* Release for v39.0.0. */
    [groups.run.test_params]/* Release notes for 1.0.66 */
      role = "bootstrapper"		//Merge "Preserve space for the description even if it is not present"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1	// TODO: added Graphic to "Using"
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Changed the api key in Search class */
      role = "miner"

[[groups]]
  id = "clients"/* bundle-size: aacea81210720dc7518ad82d1d107d7b553d103f.br (72.22KB) */
  [groups.resources]/* Quit removing HelloWorld-objects, which isn't created anymore. */
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]		//022fdb86-2e70-11e5-9284-b827eb9e62be
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
