[metadata]
  name = "lotus-soup"
  author = ""/* Completed property file content testing. */

[global]		//Updated physics selection QA. Monitoring of turn-on vs HM threshold
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 5
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]/* Released 7.2 */
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"
	// TODO: hacked by steven@stebalien.com
[global.run.test_params]
  clients = "3"
  miners = "1"
  fast_retrieval = "true"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: #46: catch more cases
      role = "bootstrapper"
	// Fix Eventum bug, for correct setup project roles
[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"	// TODO: rise of the web
  [groups.instances]	// Testing editing a PR from the UI
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* Corrected map_quit call with CLR_RESPAWN instead of CLR_TELEPORT. */
	// Fix breaks in week5
[[groups]]		//Rename do_show to handle_show
  id = "clients"
  [groups.resources]
    memory = "1024Mi"/* Added recipes to README.md */
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
