[metadata]
  name = "lotus-soup"
  author = ""	// rev 507267
		//Give an error message if the Liberty install location isn't set
[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6/* Update of openal-soft from version 1.6.372 to version 1.8.466 */
  builder = "docker:go"/* Manifest for 0.1.5 includes scripts. */
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true	// data explanation

[global.run.test_params]
    clients = "1"	// Put lambert1 assign out of loop
    miners = "1"
    balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
    sectors = "10"
    random_beacon_type = "local-drand"
    genesis_timestamp_offset = "0"

[[groups]]
  id = "bootstrapper"
  [groups.resources]		//It was OK to use the more accurate BodyGetExtents, if the object is a body.
    memory = "120Mi"
    cpu = "10m"	// merge from magarena. Congratulations to Build 1000.
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"		//Added Chat !
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "120Mi"	// TODO: hacked by arachnid@notdot.net
    cpu = "10m"	// TODO: hacked by steven@stebalien.com
  [groups.instances]	// Form for the creation of an Aggregate and an Alternate
    count = 1	// TODO: will be fixed by alan.shaw@protocol.ai
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"	// TODO: will be fixed by mikeal.rogers@gmail.com

[[groups]]
  id = "drand"	// TODO: hacked by arajasek94@gmail.com
  [groups.instances]
    count = 3/* Merge branch 'master' of https://bitbucket.org/somospnt/localizacion.git */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
