[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"		//Rename removeFromCacheOnException parameter to indicate its purpose
  runner = "local:docker"

[global.build]/* Building Build RN */
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* Release version: 0.1.30 */

[global.build_config]
  enable_go_build_cache = true
/* Merge "stagefright amrwbenc: Remove a duplicate, unused file" */
[global.run.test_params]
    clients = "1"
    miners = "1"
    balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
    sectors = "10"	// TODO: Delete test29.ring
    random_beacon_type = "local-drand"
    genesis_timestamp_offset = "0"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "120Mi"/* docs(decorators): fix typo */
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* Release 0.95.149: few fixes */
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"

[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
