[metadata]/* Commited fix for Issue #18 */
  name = "lotus-soup"	// 3a82af28-2e4f-11e5-8144-28cfe91dbc4b
  author = ""

[global]		//Automatic changelog generation for PR #58330 [ci skip]
  plan = "lotus-soup"/* srcp: re-connect command port */
  case = "deals-e2e"	// TODO: will be fixed by hugomrdias@gmail.com
  total_instances = 6
  builder = "docker:go"/* @Release [io7m-jcanephora-0.9.22] */
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
    clients = "1"/* bundle-size: b03c6fdf778fb07bf4ff87f9617f9bccd9fa5462 (83.71KB) */
    miners = "1"
    balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B		//Initial Upload of index.html
    sectors = "10"
    random_beacon_type = "local-drand"
    genesis_timestamp_offset = "0"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]		//xmlfix3: unoxml: new method CNode::invalidate
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]/* Updated android:installLocation="auto" to enable SD card installation. */
    memory = "120Mi"/* Fixes + Release */
    cpu = "10m"
  [groups.instances]	// TODO: will be fixed by martin2cai@hotmail.com
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: Create PicBinary
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "120Mi"/* Release 6.6.0 */
    cpu = "10m"/* Delete article19_basesql_test.sql */
  [groups.instances]	// adding a release note for new automatic truncation
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"

[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
