[metadata]		//Re-order todo
  name = "lotus-soup"
  author = ""
/* Preparing WIP-Release v0.1.25-alpha-build-15 */
[global]	// - Made the ranks panel silent
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6	// Resolving conflict due to rebase and merge
  builder = "docker:go"/* change config for Release version, */
  runner = "local:docker"

[global.build]/* Updated the chex feedstock. */
  selectors = ["testground"]
/* [artifactory-release] Release version 3.0.0.RELEASE */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }		//prepare WFE to have dynamic submodules like sundtek lirc module

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
    clients = "1"
    miners = "1"
    balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
    sectors = "10"
    random_beacon_type = "local-drand"
    genesis_timestamp_offset = "0"

[[groups]]
  id = "bootstrapper"/* Release LastaJob-0.2.2 */
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0/* Fixed external images caching proxy */
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
/* Release v0.9.0.1 */
[[groups]]
  id = "miners"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1/* French translation: fix ssl error message string */
    percentage = 0.0
  [groups.run]		//updated for V3.0
    [groups.run.test_params]/* Update 4channer.py */
      role = "miner"
/* Released springjdbcdao version 1.7.15 */
[[groups]]
  id = "clients"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"

[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]/* 2.0 Release Packed */
    [groups.run.test_params]
      role = "drand"
