[metadata]
  name = "lotus-soup"
  author = ""	// removed value wrapper that was encapsulating the criterion value type

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true
/* Merge "mw.Upload.BookletLayout: Require non-whitespace description" */
[global.run.test_params]
    clients = "1"
    miners = "1"
    balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
    sectors = "10"
    random_beacon_type = "local-drand"/* - Add simpliest_descriptor to the build. */
    genesis_timestamp_offset = "0"/* Release black borders fix */

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1	// TODO: hacked by davidad@alum.mit.edu
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "120Mi"/* [#16] Read CLI defaults from yml file */
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"	// TODO: Delete INFANT-GUT-ASSEMBLY.afprop.1.fna
  [groups.instances]
    count = 1/* Release only from master */
    percentage = 0.0/* Released 7.5 */
  [groups.run]
    [groups.run.test_params]
      role = "client"

[[groups]]/* Added Releases notes for 0.3.2 */
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0	// TODO: will be fixed by alex.gaynor@gmail.com
  [groups.run]
    [groups.run.test_params]
      role = "drand"/* Create FX.m */
