[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6		//Split out plan generation code.
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]
/* Update @copyright date to reflect new year */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"	// Mention license in readme file
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]		//change support link
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]	// TODO: Tests - domain
    [groups.run.test_params]
      role = "client"
