[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6/* freshRelease */
  builder = "docker:go"
  runner = "local:docker"/* Added packages. */

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }		//Update FEZ.sh

[global.build_config]
  enable_go_build_cache = true		//Update CHANGELOG for #10889

[global.run.test_params]
  clients = "3"/* Adds tests for script-based standard tools such as senders and implementors. */
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"		//passage de tableau vers arraylist

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1/* Release '0.2~ppa4~loms~lucid'. */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"/* merge patch from ubuntu */
  [groups.instances]
    count = 2/* add GPL images for anlaute2 mapping */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* Updated Readme for 4.0 Release Candidate 1 */
"larutan" = edom_gninim      

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
