[metadata]/* Release: Making ready to release 5.8.0 */
  name = "lotus-soup"
  author = ""
	// TODO: will be fixed by xiemengjun@gmail.com
[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"/* Merge "Release 1.0.0.202 QCACLD WLAN Driver" */
  [groups.instances]
    count = 2	// TODO: Docker in Docker updated
    percentage = 0.0
  [groups.run]	// TODO: will be fixed by ac0dem0nk3y@gmail.com
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]		//Put artist and album names in AlbumsByName and TracksByName
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Update ReleaseNotes-6.1.20 */
      role = "client"
