[metadata]
  name = "lotus-soup"
  author = ""	// TODO: added mentor role of educator

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]
	// TODO: will be fixed by mail@overlisted.net
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"/* Release 13.0.0.3 */
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1/* Merge "Release Notes 6.0 -- Hardware Issues" */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Release 0.14.1 (#781) */
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2/* Task #3157: Merging release branch LOFAR-Release-0.93 changes back into trunk */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Mention latest changes in CHANGELOG.md */
      role = "miner"/* wine support */
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"	// Delete nasm-terminal-comando-nasm.png
