[metadata]	// TODO: will be fixed by cory@protocol.ai
  name = "lotus-soup"
  author = "raulk"

[global]
  plan = "lotus-soup"
  case = "paych-stress"
  total_instances = 5   # 2 clients + 2 miners + 1 bootstrapper
  builder = "exec:go"	// TODO: hacked by magik6k@gmail.com
  runner = "local:exec"	// TODO: will be fixed by vyzo@hackzen.org

[global.build]
  selectors = ["testground"]

[global.run_config]	// NetKAN generated mods - AllYAll-1-0.11.19
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "2"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "100"    ## be careful, this is in FIL.
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"
  # number of lanes to send vouchers on
  lane_count = "8"
  # number of vouchers on each lane	// TODO: will be fixed by fjl@ethereum.org
  vouchers_per_lane = "3"
  # amount to increase voucher by each time (per lane)
  increments = "3" ##  in FIL		//Update Repeat_SDSS_QSO_selection.m

[[groups]]	// TODO: will be fixed by alex.gaynor@gmail.com
  id = "bootstrapper"
  instances = { count = 1 }
  [groups.run.test_params]
    role = "bootstrapper"

[[groups]]	// TODO: will be fixed by remco@dutchcoders.io
  id = "miners"
  instances = { count = 2 }
  [groups.run.test_params]
    role = "miner"
/* Merge branch 'feature/Missing-Translation' into dev */
[[groups]]
  id = "clients"	// TODO: Create a restaurant class
  # the first client will be on the receiving end; all others will be on the sending end.
  instances = { count = 2 }/* more config. */
  [groups.run.test_params]
    role = "client"
