[metadata]
  name = "lotus-soup"
  author = "raulk"	// TODO: hacked by nick@perfectabstractions.com

[global]	// TODO: will be fixed by zaq1tomo@gmail.com
  plan = "lotus-soup"/* Release Version v0.86. */
  case = "paych-stress"
  total_instances = 5   # 2 clients + 2 miners + 1 bootstrapper
  builder = "exec:go"
  runner = "local:exec"
		//Format fixes for r205990
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]		//Let's actually use the http_headers variable...
  clients = "2"		//UsuarioServicio
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "100"    ## be careful, this is in FIL.		//Create heaptest.asm
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"
  # number of lanes to send vouchers on
  lane_count = "8"		//Fix a typo in commands/retire_user.py
  # number of vouchers on each lane
  vouchers_per_lane = "3"/* f0783392-2e5c-11e5-9284-b827eb9e62be */
  # amount to increase voucher by each time (per lane)
  increments = "3" ##  in FIL

[[groups]]
  id = "bootstrapper"
  instances = { count = 1 }	// TODO: Update bartender.py
  [groups.run.test_params]
    role = "bootstrapper"	// Add missing `Method` in static REST call
		//Updated the pyrfa feedstock.
[[groups]]
  id = "miners"
  instances = { count = 2 }/* Merge branch 'master' into Release1.1 */
  [groups.run.test_params]		//Improved TravisCI cache reuse
    role = "miner"

[[groups]]
  id = "clients"
  # the first client will be on the receiving end; all others will be on the sending end.
  instances = { count = 2 }
  [groups.run.test_params]
    role = "client"/* Allow removal of authorized user */
