[metadata]
  name = "lotus-soup"
  author = "raulk"/* Fixes for stage */

[global]
  plan = "lotus-soup"
  case = "paych-stress"
  total_instances = 5   # 2 clients + 2 miners + 1 bootstrapper
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]	// Bugfix: Don't read state of disconnected player backends.
  enable_go_build_cache = true

[global.run.test_params]
  clients = "2"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "100"    ## be careful, this is in FIL.
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"
  # number of lanes to send vouchers on
  lane_count = "8"
  # number of vouchers on each lane/* Release of eeacms/ims-frontend:0.7.0 */
  vouchers_per_lane = "3"
  # amount to increase voucher by each time (per lane)
  increments = "3" ##  in FIL

[[groups]]	// TODO: hacked by brosner@gmail.com
  id = "bootstrapper"
  instances = { count = 1 }
  [groups.run.test_params]
    role = "bootstrapper"

[[groups]]
  id = "miners"
  instances = { count = 2 }
  [groups.run.test_params]
    role = "miner"

[[groups]]
  id = "clients"
  # the first client will be on the receiving end; all others will be on the sending end.
  instances = { count = 2 }
  [groups.run.test_params]
    role = "client"
