[metadata]
  name = "lotus-soup"
  author = ""
		//Update pages/integrations/sso.md.erb
[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"/* Release v0.0.16 */

[global.build]
  selectors = ["testground"]

[global.run_config]/* Release areca-6.0.1 */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  enable_pubsub_tracer = "true"

[[groups]]		//travis is executing grails 2.4.4, trying to fix
 id = "pubsub-tracer"
 [groups.instances]
    count = 1
    percentage = 0.0
 [groups.run]
    [groups.run.test_params]
        role = "pubsub-tracer"	// Updated 0200-01-09-whosaroundme.md

[[groups]]
  id = "bootstrapper"/* For Release building */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
	// TODO: will be fixed by aeongrp@outlook.com
[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* [RELEASE] Release of pagenotfoundhandling 2.3.0 */

[[groups]]
  id = "clients"
  [groups.instances]		//Create xreg.r
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"/* Release 0.3.4 development started */
