[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"	// Added pickup numbers for Ill (english)
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"
		//Bumped alias
[global.build]/* Released 2.7 */
  selectors = ["testground"]/* Release Notes: document ECN vs TOS issue clearer for 3.1 */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]	// fix bug (remove calls to $usr->administrator)
  enable_go_build_cache = true
/* fbeaa672-2e68-11e5-9284-b827eb9e62be */
[global.run.test_params]	// Queue#subscribe can now take an Executor to run non-blocking subscriptions with
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"	// TODO: will be fixed by mikeal.rogers@gmail.com
  random_beacon_type = "mock"
  enable_pubsub_tracer = "true"

[[groups]]	// TODO: hacked by peterke@gmail.com
 id = "pubsub-tracer"
 [groups.instances]
    count = 1
    percentage = 0.0
 [groups.run]
    [groups.run.test_params]
        role = "pubsub-tracer"

[[groups]]
  id = "bootstrapper"/* added netNetwork */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]/* Update CNAME with josegomezr.com.ve */
  id = "miners"
  [groups.instances]		//8756c288-2e62-11e5-9284-b827eb9e62be
    count = 2/* Updated to Netty 4.1.34.Final */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: Updated 'index.html' and 1 other files via CloudCannon
      role = "miner"	// Merge "Revert "`autocomplete` is not necessary on `search` input types""

[[groups]]/* -add missing pkgconfig generations */
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
