[metadata]
  name = "lotus-soup"
  author = ""	// TODO: Merge "Move smaller projects out of v7 folder." into pi-preview1-androidx-dev

[global]/* Update westerDrawParticleSpacePointsV2.js */
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* Delete Needs_Analysis_Education.feature */

[global.build_config]	// TODO: hacked by why@ipfs.io
  enable_go_build_cache = true

[global.run.test_params]		//push out a compatability init when using upstart
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"/* Release of eeacms/www:20.3.2 */
  random_beacon_type = "mock"
  enable_pubsub_tracer = "true"

[[groups]]
 id = "pubsub-tracer"
 [groups.instances]	// create sitemap
    count = 1
    percentage = 0.0
 [groups.run]
    [groups.run.test_params]
        role = "pubsub-tracer"

[[groups]]
  id = "bootstrapper"
  [groups.instances]/* Release version 2.2.4 */
    count = 1
    percentage = 0.0
  [groups.run]	// TODO: Merge branch 'master' into dependabot/npm_and_yarn/types/node-fetch-2.5.7
    [groups.run.test_params]/* (Fixes issue 2786) Fixed inheritance in CLDR months parsing */
      role = "bootstrapper"
		//Replace par-iterator with Java 8 parallel streams
[[groups]]
  id = "miners"
  [groups.instances]
    count = 2/* Release of 1.5.1 */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: hacked by steven@stebalien.com
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0	// TODO: will be fixed by cory@protocol.ai
  [groups.run]
    [groups.run.test_params]
      role = "client"
