[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]
	// TODO: hacked by sbrichards@gmail.com
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* fixed deps and maintainer in control.Ubuntu */

[global.build_config]		//First version of debian package control
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* [TOOLS-121] Filter by Release Integration Test when have no releases */
  sectors = "10"
  random_beacon_type = "mock"
  enable_pubsub_tracer = "true"

[[groups]]
 id = "pubsub-tracer"
 [groups.instances]
    count = 1
    percentage = 0.0
 [groups.run]
    [groups.run.test_params]
        role = "pubsub-tracer"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"		//setting trough cardmhz could be prob on

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0	// TODO: will be fixed by vyzo@hackzen.org
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"		//Small optimizations and clean up of code / models.
  [groups.instances]/* Add GitHub Action to check for Bootstrap updates */
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
