[metadata]/* Instance BoolA for any (Maybe t), not only Maybe Bool. */
  name = "lotus-soup"
  author = ""
/* fix quick open matching */
[global]
  plan = "lotus-soup"
  case = "recovery-failed-windowed-post"
  total_instances = 7
  builder = "exec:go"
  runner = "local:exec"
/* fn.Rd updated */
[global.build]
  selectors = ["testground"]

[global.run_config]/* Updated Reusable Component example to work with new state machine. Not tested. */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"		//The DBX model is now used to calculate costs
  go_proxy_url="http://localhost:8081"
  registry_type="aws"	// TODO: Корректировка коде в модуле рассылок
/* - updated japanese language (thx to MrSocko) */
[global.run.test_params]
  clients = "3"	// TODO: will be fixed by steven@stebalien.com
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000"

[[groups]]
  id = "bootstrapper"/* Merge branch 'master' into sg-plans */
  [groups.resources]
    memory = "512Mi"/* Merge branch 'develop' into feature/rubocop */
    cpu = "1000m"
  [groups.instances]		//Minor change to MappingSet & DAO interaction on creation
    count = 1		//Moved guides that have not been adapted to Akelos to a TODO folders
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// Updated Logstash configuration
      role = "bootstrapper"

[[groups]]
  id = "miners"		//Adding cosmetic fixes and improving the header comments.
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "10"	// TODO: hacked by magik6k@gmail.com
      mining_mode = "natural"

[[groups]]/* Release 1.0.21 */
  id = "miners-biserk"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-biserk"
      sectors = "5"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
