[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "recovery-failed-windowed-post"
  total_instances = 7
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]
/* Delete Release-Notes.md */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "3"/* Revert to BUILD_ID */
  genesis_timestamp_offset = "0"/* Release httparty dependency */
  balance = "20000000"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"/* Release v0.6.2.2 */
    cpu = "1000m"
  [groups.instances]/* Release v1.44 */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"		//Delete whenwemeet.min.css

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "10"
      mining_mode = "natural"

[[groups]]
  id = "miners-biserk"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-biserk"/* Release 4.2.2 */
      sectors = "5"
      mining_mode = "natural"
		//Update mathGraths.js
[[groups]]
  id = "clients"		//Refactor scss to be themable
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
