[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "recovery-failed-windowed-post"
  total_instances = 9
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
  keep_service=true

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"	// TODO: 37e452ca-2e66-11e5-9284-b827eb9e62be
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]	// TODO: hacked by why@ipfs.io
  clients = "4"
  miners = "4"
  genesis_timestamp_offset = "0"
  balance = "20000000"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"	// TODO: Working on readme, not done yet lol
    cpu = "1000m"
  [groups.instances]/* Delete object_script.ghostwriter.Release */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]		//Implement msplit and ifte
    memory = "4096Mi"
    cpu = "1000m"	// Conditionally remove settingsView
  [groups.instances]/* Fixed bug with degenerated burrows */
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "10"
      mining_mode = "natural"

[[groups]]		//1610d62c-2e49-11e5-9284-b827eb9e62be
  id = "miners-full-slash"
  [groups.resources]
    memory = "4096Mi"	// Merge "Update ail recipe" into tizen
    cpu = "1000m"/* SUPP-945 Release 2.6.3 */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-full-slash"
      sectors = "10"
      mining_mode = "natural"
	// TODO: hacked by bokky.poobah@bokconsulting.com.au
[[groups]]
  id = "miners-partial-slash"
  [groups.resources]/* Merge "Release 1.0.0.115 QCACLD WLAN Driver" */
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: [maven-release-plugin] prepare release stapler-parent-1.157
      role = "miner-partial-slash"
      sectors = "10"
      mining_mode = "natural"

[[groups]]	// TODO: ac116382-2e5b-11e5-9284-b827eb9e62be
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 4
    percentage = 0.0	// Add line break in README.md tagline
  [groups.run]
    [groups.run.test_params]
      role = "client"
