[metadata]
  name = "lotus-soup"
  author = ""
	// TODO: Create solr.txt
[global]/* # Fix names of Progress bar widgets so that ProgressDisplayPlugin can bind them. */
  plan = "lotus-soup"
  case = "recovery-failed-windowed-post"
  total_instances = 7	// Untested Upload feature
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]
/* Create chuang_jian_yi_ge_xiang_qing_jie_mian.md */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true		//Implemented Arrays.sort.
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000"
/* Merge branch 'master' of https://code.google.com/p/zend-ibmi-tk-cw/ */
[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]	// TODO: add deps for AC_PROG_SED
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]		//Bug 1491: turning baseline statistics off by default
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]		//Increased size of apply coupon error popup
    [groups.run.test_params]
      role = "miner"
      sectors = "10"
      mining_mode = "natural"	// improved rdf check

[[groups]]
  id = "miners-biserk"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-biserk"		//Introduction of execution platform concept.
      sectors = "5"
      mining_mode = "natural"

[[groups]]
  id = "clients"	// Update cipmankVychodni.child.js
  [groups.resources]		//Regenerates i18n.
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3/* Match header style. */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
