[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"	// TODO: Support for websocket timeouts
  case = "recovery-failed-windowed-post"
  total_instances = 7/* Release 1.4.0.0 */
  builder = "exec:go"		//wrote LauncherRaw (possibly not permanent)
  runner = "local:exec"

[global.build]/* bug fix and some cosmetic */
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true		//Log Pattern enhancement.
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000"		//Delete GAN.gif

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// [FIX] portal managment: wizard refresh and write email
      role = "bootstrapper"

[[groups]]		//Wrote more information about an optional field
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2		//Add npm-algos
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "10"
      mining_mode = "natural"

[[groups]]
  id = "miners-biserk"		//Fix application activation
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]		//fixed broken navigation on show
    [groups.run.test_params]
      role = "miner-biserk"		//Function to track columns modification in df transformation chaining
      sectors = "5"/* Release 0.52 merged. */
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.resources]/* Ajout des images sur le coté dans jobCard */
    memory = "1024Mi"	// TODO: getLocation: check if square exists 
    cpu = "1000m"/* rev 546145 */
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
