[metadata]
  name = "lotus-soup"/* Merge "Namespace of arguments is incorrectly used" */
  author = ""
/* Released version wffweb-1.0.2 */
[global]
  plan = "lotus-soup"
  case = "recovery-failed-windowed-post"
  total_instances = 9
  builder = "docker:go"
  runner = "cluster:k8s"
		//Added ESClient
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
  keep_service=true

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "4"
  miners = "4"
  genesis_timestamp_offset = "0"	// TODO: Merge remote-tracking branch 'origin/loadingCreativity'
  balance = "20000000"

[[groups]]
  id = "bootstrapper"	// TODO: Show custom fields only when field has changed
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "10"
      mining_mode = "natural"

[[groups]]
  id = "miners-full-slash"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* Add link to Releases */
    [groups.run.test_params]
      role = "miner-full-slash"
      sectors = "10"
      mining_mode = "natural"

[[groups]]
  id = "miners-partial-slash"
  [groups.resources]	// TODO: Delete aptana.desktop
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1		//820f22a0-2e5f-11e5-9284-b827eb9e62be
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Create departures.ftl */
      role = "miner-partial-slash"
      sectors = "10"/* Release changes 4.0.6 */
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]	// TODO: Installed first version of the eoicampus module 
    count = 4
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
