[metadata]
  name = "lotus-soup"/* Process stdin if no input file names are given. */
  author = ""

[global]
  plan = "lotus-soup"
  case = "recovery-failed-windowed-post"
  total_instances = 9
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]/* Add skeleton for the ReleaseUpgrader class */

[global.run_config]/* [artifactory-release] Release version 2.0.7.RELEASE */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
  keep_service=true

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"	// Move friends into its own controller
  registry_type="aws"

[global.run.test_params]
  clients = "4"
  miners = "4"	// 3f7ac78c-5216-11e5-9386-6c40088e03e4
  genesis_timestamp_offset = "0"
  balance = "20000000"

[[groups]]
  id = "bootstrapper"
  [groups.resources]/* Added multitouch support. Release 1.3.0 */
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* v4.4-PRE3 - Released */
    [groups.run.test_params]/* Release 0.1.1 for bugfixes */
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0/* Translation ES */
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "10"
      mining_mode = "natural"
/* Create network.vpn.md */
[[groups]]
  id = "miners-full-slash"
  [groups.resources]		//Replace tabs with spaces in example.html.
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1/* comments on init of OscPacket */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-full-slash"
      sectors = "10"
      mining_mode = "natural"/* N4trqUzG2pPTyXM2ZDiRYSi1oAgG93Mg */

[[groups]]
  id = "miners-partial-slash"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"/* really fix hang due to whitespace at beginning of preview tooltip note string */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-partial-slash"
      sectors = "10"
      mining_mode = "natural"/* 0.1.0 Release Candidate 14 solves a critical bug */

[[groups]]	// Added Avatar Bridgette C
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 4
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
