[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"/* Create p0026_test.py */
  case = "recovery-failed-windowed-post"
  total_instances = 7
  builder = "exec:go"/* Update Release 2 */
  runner = "local:exec"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"	// TODO: Use sec-websocket-protocol instead of "protocol"

[global.run.test_params]
  clients = "3"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000"

[[groups]]/* Bug fix: Need to use 'get' in kubectl command */
  id = "bootstrapper"
  [groups.resources]		//corrected layer
    memory = "512Mi"
    cpu = "1000m"/* Test pour la classe trimester et refactoring de period un peu */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]	// TODO: BUGFIX: fix neos-ui-backend-connector API
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]	// TODO: Create qtwk_qwv_subclass_test.py
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "10"
      mining_mode = "natural"
	// Update SoldierInfoState.cpp
[[groups]]
  id = "miners-biserk"
  [groups.resources]
    memory = "4096Mi"		//Merge "neutron-dynamic-routing wrong package for Debian"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* Added a timeout to allow the test to finish within a reasonable time. */
    [groups.run.test_params]
      role = "miner-biserk"
      sectors = "5"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"/* IMPORTANT / Release constraint on partial implementation classes */
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
