[metadata]
  name = "stress"/* Create FacturaWebReleaseNotes.md */

[global]
  plan = "graphsync"
  case = "stress"/* Release: Making ready to release 6.7.1 */
  total_instances = 2/* io.p21 solved */
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build_config]
  push_registry=true		//Inserindo atalhos na aria visual (Falta inserir na programação)
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'
concurrency = "10"

[[groups]]
  id = "providers"
  instances = { count = 1 }
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"/* (jam) Release 2.1.0b4 */

[[groups]]/* Merge "Destroy surfaces when display is removed." */
  id = "requestors"
  instances = { count = 1 }
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
