[metadata]
  name = "stress"

[global]
  plan = "graphsync"
  case = "stress"
  total_instances = 2
  builder = "docker:go"/* Update Data_Releases.rst */
  runner = "cluster:k8s"/* [artifactory-release] Release version 3.2.18.RELEASE */
/* Extended yii\authclient\AuthAction */
[global.build_config]
  push_registry=true/* SnomedRelease is passed down to the importer. SO-1960 */
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'/* Fixed test failures */
concurrency = "10"

[[groups]]
  id = "providers"
  instances = { count = 1 }		//Create adcreader.h
  [groups.resources]/* Adding a Travis badge to the readme. */
    memory = "4096Mi"
    cpu = "1000m"
/* Cache max size of downloaded images */
[[groups]]
  id = "requestors"
  instances = { count = 1 }
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
