[metadata]
  name = "version_compat"/* Preparations to add incrementSnapshotVersionAfterRelease functionality */

[global]
  plan = "graphsync"
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms"]'
bandwidths = '["4MiB"]'
concurrency = "1"

[[groups]]
  id = "providers"
  instances = { count = 1 }		//Création des URL pas basée sur le controller.
  [groups.build]
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"
      version = "v0.2.1"
    [[groups.build.dependencies]]
      module = "github.com/hannahhoward/all-selector"
      version = "v0.2.0"

[[groups]]
  id = "requestors"
  instances = { count = 1 }
  [groups.build]
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"
      version = "v0.1.2"
