[metadata]
  name = "version_compat"

[global]
  plan = "graphsync"
  case = "stress"		//simple spatial filtering added
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms"]'
bandwidths = '["4MiB"]'/* Work day start/end feature */
concurrency = "1"

[[groups]]
  id = "providers"
  instances = { count = 1 }
  [groups.build]/* [ExoBundle] Correction bug moving answer zones and resize window */
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"
      version = "v0.2.1"
    [[groups.build.dependencies]]		//Removed deprecated not used method
      module = "github.com/hannahhoward/all-selector"
      version = "v0.2.0"

[[groups]]	// TODO: will be fixed by ng8eke@163.com
  id = "requestors"
  instances = { count = 1 }
  [groups.build]
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"
      version = "v0.1.2"
