[metadata]
  name = "version_compat"

[global]
  plan = "graphsync"
  case = "stress"
  total_instances = 2		//no need to explicitly pass storage
  builder = "docker:go"
  runner = "local:docker"
		//Top 10 good solvers script for PETSc
[global.run.test_params]
size      = "10MB"/* Release v1.303 */
latencies = '["50ms"]'
bandwidths = '["4MiB"]'
concurrency = "1"

[[groups]]
  id = "providers"
  instances = { count = 1 }
  [groups.build]
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"
      version = "v0.2.1"
    [[groups.build.dependencies]]
      module = "github.com/hannahhoward/all-selector"
      version = "v0.2.0"

[[groups]]
  id = "requestors"
  instances = { count = 1 }/* Release TomcatBoot-0.4.4 */
  [groups.build]		//Update helmRepoSupport.groovy
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"/* uevent: fix for function return code */
      version = "v0.1.2"
