[metadata]
  name = "version_compat"

[global]	// TODO: hacked by admin@multicoin.co
  plan = "graphsync"
  case = "stress"
  total_instances = 2		//Better variable arity.
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms"]'
bandwidths = '["4MiB"]'/* Delete employees.html */
concurrency = "1"
	// Added some emoji.
[[groups]]/* target-Ordner leeren, aber nicht löschen (ermöglicht Nutzung eines Symlinks) */
  id = "providers"
  instances = { count = 1 }
  [groups.build]
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"
      version = "v0.2.1"
    [[groups.build.dependencies]]
      module = "github.com/hannahhoward/all-selector"
      version = "v0.2.0"	// TODO: will be fixed by brosner@gmail.com
/* Fix typo in Cascadia Code README */
[[groups]]
  id = "requestors"
  instances = { count = 1 }
  [groups.build]
    [[groups.build.dependencies]]	// 59e17222-2e48-11e5-9284-b827eb9e62be
      module = "github.com/ipfs/go-graphsync"
      version = "v0.1.2"
