name = "lotus-testground"
extra_sources = { "exec:go" = ["../extra/filecoin-ffi"] }

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."exec:go"]
enabled = true

[builders."docker:go"]
enabled = true
build_base_image = "iptestground/oni-buildbase:v1"
runtime_image = "iptestground/oni-runtime:v1"
enable_go_build_cache = true
skip_runtime_image = false

[runners."local:exec"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."cluster:k8s"]
enabled = true

# seq 0
[[testcases]]
name = "lotus-network"
instances = { min = 5, max = 5, default = 5 }

[testcases.params]
   miner-count = { type = "int", default = 2 }
