name: lotus
base: core18
version: '1.8.0'
summary: filecoin daemon/client
description: |
  Filecoin is a peer-to-peer network that stores files on the internet
  with built-in economic incentives to ensure files are stored reliably over time
grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  libs:
    plugin: dump
    source: ./
    organize:
      'lotus' : bin/
      'lotus-*' : bin/
    stage-packages:
      - ocl-icd-libopencl1
      - libhwloc1
      - libgcc1
apps:
  lotus:
    command: bin/lotus
  lotus-miner:
    command: bin/lotus-miner
  lotus-worker:
    command: bin/lotus-worker
