[metadata]	// Fixed ConVar issue
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"/* Rename 09_Apply.rst to 10_Apply.rst */
  total_instances = 7
  builder = "docker:go"/* Release jedipus-2.6.3 */
  runner = "local:docker"
	// TODO: try to get firebird stuff working with 0.6.6
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "5"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "5"
  random_beacon_type = "mock"
  mining_mode = "natural"	// TODO: will be fixed by timnugent@gmail.com

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]	// TODO: hacked by caojiaoyue@protonmail.com
    [groups.run.test_params]	// TODO: will be fixed by zaq1tomo@gmail.com
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]	// TODO: will be fixed by fkautz@pseudocode.cc
    count = 1
    percentage = 0.0
  [groups.run]		//tweaked nfar minimal damage
    [groups.run.test_params]
      role = "miner"
      latency_range = '["20ms", "300ms"]'

[[groups]]
  id = "clients"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      latency_range = '["100ms", "1500ms"]'
