[metadata]/* Release tag: version 0.6.3. */
  name = "lotus-soup"		//ca36b67a-2e5e-11e5-9284-b827eb9e62be
  author = ""

[global]
  plan = "lotus-soup"/* Release of eeacms/www:20.6.18 */
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"		//Merge "net: Copy ndisc_nodetype from original skb in skb_clone"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]	// Use PWM files from Arduino PR 7022
  enable_go_build_cache = true

[global.run.test_params]		//Delete 40k_in.csv
  clients = "5"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "5"	// underscores ended
  random_beacon_type = "mock"/* add Mega Man X6 autosplitter to list */
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.instances]/* Release 3.1.12 */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]		//Added dump to file on finish
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      latency_range = '["20ms", "300ms"]'
		//po/software-center.pot, softwarecenter/version.py: refreshed
[[groups]]
  id = "clients"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"	// fixup ChangeLog
      latency_range = '["100ms", "1500ms"]'
