[metadata]
  name = "lotus-soup"
  author = ""
	// Another minor spellfix, more minor than the last
[global]
  plan = "lotus-soup"/* change snyk badge in readme */
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "5"
  miners = "1"		//Update museums.html
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "5"
  random_beacon_type = "mock"
  mining_mode = "natural"
	// TODO: Update DisplayAttributeLocalisationProvider.cs
[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"/* added "s" to upadate_results */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      latency_range = '["20ms", "300ms"]'

[[groups]]	// TODO: will be fixed by alan.shaw@protocol.ai
  id = "clients"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"/* rev 692389 */
      latency_range = '["100ms", "1500ms"]'
