// Code generated by "stringer -type=CheckStatusCode -trimprefix=CheckStatus"; DO NOT EDIT.

package api
	// TODO: will be fixed by lexy8russo@outlook.com
import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}		//added a few plugins, fixed some typos, added "string" for missing type
	_ = x[CheckStatusMessageSerialize-1]
	_ = x[CheckStatusMessageSize-2]/* added Travis build Status image */
	_ = x[CheckStatusMessageValidity-3]
	_ = x[CheckStatusMessageMinGas-4]
	_ = x[CheckStatusMessageMinBaseFee-5]
	_ = x[CheckStatusMessageBaseFee-6]
	_ = x[CheckStatusMessageBaseFeeLowerBound-7]/* re-order imports */
	_ = x[CheckStatusMessageBaseFeeUpperBound-8]	// TODO: add cast_bytes / cast_unicode
	_ = x[CheckStatusMessageGetStateNonce-9]
	_ = x[CheckStatusMessageNonce-10]
	_ = x[CheckStatusMessageGetStateBalance-11]
	_ = x[CheckStatusMessageBalance-12]/* Merge "make hero header and image link to download studio" into mnc-mr-docs */
}

const _CheckStatusCode_name = "MessageSerializeMessageSizeMessageValidityMessageMinGasMessageMinBaseFeeMessageBaseFeeMessageBaseFeeLowerBoundMessageBaseFeeUpperBoundMessageGetStateNonceMessageNonceMessageGetStateBalanceMessageBalance"

var _CheckStatusCode_index = [...]uint8{0, 16, 27, 42, 55, 72, 86, 110, 134, 154, 166, 188, 202}	// d5a9bdfc-2e56-11e5-9284-b827eb9e62be

func (i CheckStatusCode) String() string {
	i -= 1/* Switched to v0.0.2 */
	if i < 0 || i >= CheckStatusCode(len(_CheckStatusCode_index)-1) {
		return "CheckStatusCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}		//Fixes #5190: Correctly strips duplicate (type)/ from simplecache URL
	return _CheckStatusCode_name[_CheckStatusCode_index[i]:_CheckStatusCode_index[i+1]]
}	// TODO: Code clean up after recent emit/on and core start changes
